---CUSTOMER STATIC DETAILS LIKE AGE, TENURE
WITH cust AS 
(

SELECT 
	CUSTOMER_NUMBER,
	--Cust_contact_Date,
	--COALESCE(DATE_OF_BIRTH, DATE_OF_BIRTHS, BIRTH_INCORP_DATE) AS DOB,
	
    DATEDIFF(YEAR, COALESCE(DATE_OF_BIRTH, DATE_OF_BIRTHS, BIRTH_INCORP_DATE), GETDATE()) - 
          CASE 
              WHEN MONTH(COALESCE(DATE_OF_BIRTH, DATE_OF_BIRTHS, BIRTH_INCORP_DATE)) > MONTH(GETDATE()) 
                   OR (MONTH(COALESCE(DATE_OF_BIRTH, DATE_OF_BIRTHS, BIRTH_INCORP_DATE)) = MONTH(GETDATE()) 
                       AND DAY(COALESCE(DATE_OF_BIRTH, DATE_OF_BIRTHS, BIRTH_INCORP_DATE)) > DAY(GETDATE())) 
              THEN 1 
              ELSE 0 
          END AS AGE,
     DATEDIFF(MONTH, Cust_contact_Date, GETDATE()) cust_tenure_months
	
FROM SVUPHSIQDBPR.dbcba.KE_Customer_Master
WHERE EXTRACTION_DATE = (SELECT MAX(EXTRACTION_DATE) FROM SVUPHSIQDBPR.dbcba.KE_Customer_Master)
AND BUSINESS_SEGMENT IN ('250', '270')
--ORDER BY cust_tenure_months DESC

),

acc AS 
(
SELECT 
	CUSTOMER,
	ACCOUNT_NUMBER

FROM dbcba.ke_Accounts_Master
WHERE EXTRACTION_DATE = (SELECT MAX(EXTRACTION_DATE) FROM dbcba.ke_Accounts_Master)
AND PRODUCT_LINE = 'ACCOUNTS'
--AND ARR_STATUS = 'CURRENT'

)

SELECT
	DISTINCT(cust.CUSTOMER_NUMBER) AS CUSTOMER_NUMBER,
	cust.AGE,
	cust.cust_tenure_months

FROM cust
INNER JOIN  acc
ON
acc.CUSTOMER = cust.CUSTOMER_NUMBER