with LFALoansDasboard as
 (
select CAST(am.EXTRACTION_DATE AS DATE) as EXTRACTION_DATE ,cm.CUS_SHORT_NAME, am.CUSTOMER,am.ARRANGEMENT_ID,am.ACCOUNT_NUMBER,
case 
	when stl.PAYOUT_ACCOUNT is null or stl.PAYOUT_ACCOUNT='' then stl.PAYIN_ACCOUNT 
	else stl.PAYOUT_ACCOUNT 
end as SETTLEMENT_ACCOUNT,
cm.CLASSIFICATION,am.CATEGORY_DESC,am.CURRENCY,am.INTEREST_RATE,(COALESCE (am.ONLINE_ACTUAL_BAL,0)*-1)/1000 as [ONLINE_ACTUAL_BAL_Kes_000], CONVERT(DECIMAL(18,0),am.TERM_AMOUNT)/1000 as [DISBURSED_AMT_Kes_000], 
CONVERT(DECIMAL(18,0),ex.Deal_balance) as EXPOSURE_ACTUAL, 
case 
	when am.CURRENCY ='KES' then CONVERT(DECIMAL(18,0),ex.Deal_balance)
	else CONVERT(DECIMAL(18,0),ex.Deal_balance)*am.EXCHANGE_RATE
end as EXPOSURE_KES,
CONVERT(DECIMAL(18,0),(COALESCE (pdo.ARREARS_AMOUNT ,0)) ) AS ARREARS_KES, COALESCE (pdo.Days_In_Arrears ,0) as OD_DAYS,
DATE(am.VALUE_DATE) as VALUE_DATE, DATE(am.MATURITY_DATE ) as MATURITY_DATE,DATE(am.PAYMENT_START_DATE) as PAYMENT_START_DATE,
CASE MONTH(am.PAYMENT_START_DATE)
        WHEN 1 THEN 'January'
        WHEN 2 THEN 'February'
        WHEN 3 THEN 'March'
        WHEN 4 THEN 'April'
        WHEN 5 THEN 'May'
        WHEN 6 THEN 'June'
        WHEN 7 THEN 'July'
        WHEN 9 THEN 'September'
        WHEN 8 THEN 'August'
        WHEN 10 THEN 'October'
        WHEN 11 THEN 'November'
        WHEN 12 THEN 'December'
    END + STR(YEAR(am.PAYMENT_START_DATE)) AS [PAYMENT START MONTH],
    CASE MONTH(am.VALUE_DATE)
        WHEN 1 THEN 'January'
        WHEN 2 THEN 'February'
        WHEN 3 THEN 'March'
        WHEN 4 THEN 'April'
        WHEN 5 THEN 'May'
        WHEN 6 THEN 'June'
        WHEN 7 THEN 'July'
        WHEN 8 THEN 'August'
        WHEN 9 THEN 'September'
        WHEN 10 THEN 'October'
        WHEN 11 THEN 'November'
        WHEN 12 THEN 'December'
    END + STR(YEAR(am.VALUE_DATE)) AS [LOAN BOOKING MONTH],
am.REPAYMENT_AMT AS EMI,
DATEDIFF(MONTH,CONVERT(DATE,am.VALUE_DATE),CURRENT_TIMESTAMP) as MOB,
 am.ARR_STATUS AS LOAN_STATUS, 
 CASE
 	when  am.ARR_STATUS IN ('CURRENT','EXPIRED') AND OD_DAYS<31then 'NORMAL'
	when am.ARR_STATUS IN ('CURRENT','EXPIRED') AND OD_DAYS<91 then 'WATCH'
	when am.ARR_STATUS IN ('CURRENT','EXPIRED') AND OD_DAYS>90 then 'NPL'
	ELSE 'CLOSED'
 END AS [LIVE CLASSIFICATIONS], 
 CASE
 	when  am.VALUE_DATE < '2024-07-01' then 'OLD UPLOAD'
 	when  am.VALUE_DATE between '2024-07-01' and '2024-11-20' then 'PILOT UPLOAD'
 	when  am.VALUE_DATE >= '2024-11-21' then 'POST GO LIVE'
 END AS [UPLOAD COHORTS], 
  CASE
 	when  am.ARR_STATUS IN ('CURRENT','EXPIRED') AND OD_DAYS<31then (COALESCE (AM.ONLINE_ACTUAL_BAL,0)*-1)/1000 
		ELSE 0
 END AS [NORMAL PR_BALANCE_Kes_000], 
 CASE
 	when  am.ARR_STATUS IN ('CURRENT','EXPIRED') AND OD_DAYS BETWEEN 31 AND 90 then (COALESCE (AM.ONLINE_ACTUAL_BAL,0)*-1)/1000
		ELSE 0
 END AS [PAR PR_BALANCE_Kes_000], 
 CASE
 	when  am.ARR_STATUS IN ('CURRENT','EXPIRED') AND OD_DAYS>90 then (COALESCE (AM.ONLINE_ACTUAL_BAL,0)*-1)/1000
		ELSE 0
 END AS [NPL PR_BALANCE_Kes_000], 
case 
	when cm.BUSINESS_SEGMENT in ('270','250') then 'CONSUMER BANKING'
	when cm.BUSINESS_SEGMENT in ('200') then 'COMMERCIAL & BUSINESS BANKING'
end as BUSINESS_UNIT,
cm.SUB_SEGEMENT_DESC, cm.CUSTOMER_BRANCH_NAME ,cm.ACCOUNT_OFFICER_NAME,
CASE
	WHEN DATE(am.PAYMENT_START_DATE)<current_timestamp then 'REPAYMENT_STARTED'
	else 'GRACE PERIOD'
END as [REPAYMENT STATUS],
Case
	when OD_DAYS=0 then 'Zero DPD'
	when OD_DAYS <16 then 'DPD_ 1-15'
	when OD_DAYS<31 then 'DPD_16-30'
	when OD_DAYS<46 then 'DPD_31-45'
	when OD_DAYS<61 then 'DPD_46-60'
	when OD_DAYS<75then 'DPD_61-75'
	when OD_DAYS<91 then 'DPD_76-90'
	when OD_DAYS>90 then 'DPD_>90 (NPL)'
END as [OD DAYS SEGMENTS],
Case
	when ARREARS_KES>0 then 'WITH ARREARS'
	ELSE 'NO ARREARS'
	END as [ARRERAS STATUS],
cm.CUST_MOB_PHONE, cm.CUST_EMAIL_ID,
ROW_NUMBER() OVER ( PARTITION BY am.ACCOUNT_NUMBER,DATEFORMAT(am.EXTRACTION_DATE,'yyyy-mm') ORDER BY am.EXTRACTION_DATE DESC) AS rn --latest entry
FROM dbcba.KE_Accounts_Master am
	INNER JOIN (
  				SELECT * 
  				fROM dbcba.KE_Customer_Master
  				WHERE EXTRACTION_DATE = (SELECT MAX(processing_date) FROM dbcba.end_of_day)
				) cm
		on am.CUSTOMER =cm.CUSTOMER_NUMBER   
		LEFT JOIN stgke.STG_ECB_TOTAL_EXPOSURE ex 
		on am.ACCOUNT_NUMBER=ex.RECID and ex.LOAD_DATE=am.EXTRACTION_DATE
	left join stgke.STG_AA_ARR_SETTLEMENT stl
		on stl.ID_COMP_1=am.ARRANGEMENT_ID
	left join(select * from STGKE.STG_AA_ARREARS 
				where EXTRACTION_DATE = (select max(EXTRACTION_DATE) from STGKE.STG_AA_ARREARS)) pdo
		on am.ARRANGEMENT_ID=pdo.ARRANGEMENT_ID 
where am.CATEGORY='3765'
AND am.PRODUCT_LINE = 'LENDING' 
and am.CATEGORY='3765' 
and cm.CLASSIFICATION <>'B20' and am.ARR_STATUS<>'AUTH' 
and cm.BUSINESS_SEGMENT not in ('260') 
AND (am.VALUE_DATE >= '2024-03-01' OR am.VALUE_DATE IS NULL)
AND am.ONLINE_ACTUAL_BAL <= 0

) 
select top 10
MAX(EXTRACTION_DATE) AS MONTH_END,
cast(SUM([DISBURSED_AMT_Kes_000]) as decimal(18,2)),
cast(SUM([ONLINE_ACTUAL_BAL_Kes_000]) as decimal(12,2)),
cast(sum([PAR PR_BALANCE_Kes_000])as decimal(12,2)),
cast(sum([NPL PR_BALANCE_Kes_000])as decimal(12,2)),
cast(sum([PAR PR_BALANCE_Kes_000])/SUM([DISBURSED_AMT_Kes_000]) as decimal(12,2)) AS PAR, 
cast(sum([NPL PR_BALANCE_Kes_000])/SUM([DISBURSED_AMT_Kes_000]) as decimal(12,2)) AS NPL
FROM
LFALoansDasboard 
where rn = 1
GROUP BY DATEFORMAT(EXTRACTION_DATE,'yyyy-mm')
order by MONTH_END DESC













