---LOAN TO INCOME RATIO - Simple average income 
WITH ctos AS (
SELECT
    BOOKING_DATE,
    CUSTOMER_ID,
    AMOUNT_LCY

FROM
    dbcba.KE_ACCOUNT_TRANSACTIONS
WHERE
    BOOKING_DATE <= DATEADD(DAY, -(DAY(GETDATE())), CAST(GETDATE() AS DATE))  -- Current day of the month --removes the days of incomplete current month
    AND BOOKING_DATE >= DATEADD(MONTH, -12, DATEADD(DAY, -(DAY(GETDATE()) - 1), CAST(GETDATE() AS DATE))) -- One year back, minus current day minus 1
	--BOOKING_DATE BETWEEN '2025-01-01' AND '2025-01-31'
    AND AMOUNT_LCY > 0
    --AND txn_code_initiation = 'CUSTOMER'
    AND (DEBIT_CUSTOMER <> CREDIT_CUSTOMER OR DEBIT_CUSTOMER IS NULL) --Remove inter-account transfers
    AND (CUSTOMER_ID IS NOT NULL OR CUSTOMER_ID <> ' ')
    AND TRANSACTION_CODE NOT IN ('1001', '944', '945''1085','766','949','945','991','941','433','1006',
    '85','234','859','940','992','947','939','946','944','948','938','1001', '967') --Remove loan disbursements, unpaid cheques
    AND SYSTEM_ID NOT IN ('AA') -- Remove credits from Fixed Deposits and any other AA module txns
    AND REVERSAL_MARKER <> 'R'
    --AND CUSTOMER_ID IN ('100001')
ORDER BY BOOKING_DATE ASC

),

monthly_ctos AS 
(

SELECT 
	CUSTOMER_ID,
    SUM(CASE WHEN DATENAME(MONTH, BOOKING_DATE) = DATENAME(MONTH, DATEADD(MONTH, -1, GETDATE())) THEN AMOUNT_LCY ELSE 0 END) AS [Month_1_CTO],
    SUM(CASE WHEN DATENAME(MONTH, BOOKING_DATE) = DATENAME(MONTH, DATEADD(MONTH, -2, GETDATE())) THEN AMOUNT_LCY ELSE 0 END) AS [Month_2_CTO],
    SUM(CASE WHEN DATENAME(MONTH, BOOKING_DATE) = DATENAME(MONTH, DATEADD(MONTH, -3, GETDATE())) THEN AMOUNT_LCY ELSE 0 END) AS [Month_3_CTO],
    SUM(CASE WHEN DATENAME(MONTH, BOOKING_DATE) = DATENAME(MONTH, DATEADD(MONTH, -4, GETDATE())) THEN AMOUNT_LCY ELSE 0 END) AS [Month_4_CTO],
    SUM(CASE WHEN DATENAME(MONTH, BOOKING_DATE) = DATENAME(MONTH, DATEADD(MONTH, -5, GETDATE())) THEN AMOUNT_LCY ELSE 0 END) AS [Month_5_CTO],
    SUM(CASE WHEN DATENAME(MONTH, BOOKING_DATE) = DATENAME(MONTH, DATEADD(MONTH, -6, GETDATE())) THEN AMOUNT_LCY ELSE 0 END) AS [Month_6_CTO],
    SUM(CASE WHEN DATENAME(MONTH, BOOKING_DATE) = DATENAME(MONTH, DATEADD(MONTH, -7, GETDATE())) THEN AMOUNT_LCY ELSE 0 END) AS [Month_7_CTO],
    SUM(CASE WHEN DATENAME(MONTH, BOOKING_DATE) = DATENAME(MONTH, DATEADD(MONTH, -8, GETDATE())) THEN AMOUNT_LCY ELSE 0 END) AS [Month_8_CTO],
    SUM(CASE WHEN DATENAME(MONTH, BOOKING_DATE) = DATENAME(MONTH, DATEADD(MONTH, -9, GETDATE())) THEN AMOUNT_LCY ELSE 0 END) AS [Month_9_CTO],
    SUM(CASE WHEN DATENAME(MONTH, BOOKING_DATE) = DATENAME(MONTH, DATEADD(MONTH, -10, GETDATE())) THEN AMOUNT_LCY ELSE 0 END) AS [Month_10_CTO],
    SUM(CASE WHEN DATENAME(MONTH, BOOKING_DATE) = DATENAME(MONTH, DATEADD(MONTH, -11, GETDATE())) THEN AMOUNT_LCY ELSE 0 END) AS [Month_11_CTO],
    SUM(CASE WHEN DATENAME(MONTH, BOOKING_DATE) = DATENAME(MONTH, DATEADD(MONTH, -12, GETDATE())) THEN AMOUNT_LCY ELSE 0 END) AS [Month_12_CTO]
	
FROM ctos
GROUP BY CUSTOMER_ID
),

avg_ctos AS 
(
SELECT 
	--monthly_ctos.*,
	CUSTOMER_ID,
	ROUND((Month_1_CTO+Month_2_CTO+Month_3_CTO+Month_4_CTO+Month_5_CTO+Month_6_CTO+Month_7_CTO+Month_8_CTO+Month_9_CTO+Month_10_CTO+Month_11_CTO+Month_12_CTO)/
	((CASE WHEN Month_1_CTO >0 THEN 1 ELSE 0 END)+(CASE WHEN Month_2_CTO >0 THEN 1 ELSE 0 END)+(CASE WHEN Month_3_CTO >0 THEN 1 ELSE 0 END)+
	(CASE WHEN Month_4_CTO >0 THEN 1 ELSE 0 END)+(CASE WHEN Month_5_CTO >0 THEN 1 ELSE 0 END)+(CASE WHEN Month_6_CTO >0 THEN 1 ELSE 0 END)+
	(CASE WHEN Month_7_CTO >0 THEN 1 ELSE 0 END)+(CASE WHEN Month_8_CTO >0 THEN 1 ELSE 0 END)+(CASE WHEN Month_9_CTO >0 THEN 1 ELSE 0 END)+
	(CASE WHEN Month_10_CTO >0 THEN 1 ELSE 0 END)+(CASE WHEN Month_11_CTO >0 THEN 1 ELSE 0 END)+(CASE WHEN Month_12_CTO >0 THEN 1 ELSE 0 END)),2) AS avg_income

FROM monthly_ctos 
),

term_loans AS 

(
SELECT
    --DISTINCT A.ACCOUNT_NUMBER AS ACCOUNT_NUMBER,
    --CAST(A.ARR_START_DATE AS DATE) AS ARR_START_DATE,
    DISTINCT(A.CUSTOMER) AS CUSTOMER,
    --A.ARR_PRODUCT_STATUS,
    --A.TERM_AMOUNT,
    SUM(CASE
        WHEN A.REPAYMENT_AMT IS NULL OR A.REPAYMENT_AMT = '' THEN 0
        ELSE CAST(A.REPAYMENT_AMT AS DOUBLE) * A.EXCHANGE_RATE
    END) AS REPAYMENT_AMT,
    SUM(CASE
        WHEN A.ACCOUNT_NUMBER = D.ACCOUNT_NUMBER THEN D.EXPOSURE_KES
        ELSE A.ONLINE_ACTUAL_BAL * -1
    END) AS SUM_EXPOSURE_ACTUAL
    --A.SCHEME_INS_PART,
    --A.NIC_SCHEMES,
    /*
    CASE
        WHEN A.SCHEME_INS_PART <> '' THEN A.SCHEME_INS_PART
        ELSE A.NIC_SCHEMES
    END AS SCHEME_ID
    */
FROM
    DBCBA.KE_ACCOUNTS_MASTER A
LEFT JOIN DBCBA.KE_CUSTOMER_MASTER B 
    ON A.CUSTOMER = B.CUSTOMER_NUMBER
    AND B.EXTRACTION_DATE = (
        SELECT MAX(EXTRACTION_DATE) FROM DBCBA.KE_CUSTOMER_MASTER
    )
LEFT JOIN STGKE.STG_AA_ARREARS C 
    ON A.ACCOUNT_NUMBER = C.ACCOUNT_NUMBER
    AND C.EXTRACTION_DATE = (
        SELECT MAX(EXTRACTION_DATE) FROM STGKE.STG_AA_ARREARS
    )
LEFT JOIN STGKE.STG_AA_BILL_ARREARS D 
    ON A.ARRANGEMENT_ID = D.ARRANGEMENT_ID
    AND D.EXTRACTION_DATE = (
        SELECT MAX(EXTRACTION_DATE) FROM STGKE.STG_AA_BILL_ARREARS
    )
WHERE
    A.EXTRACTION_DATE = (
        SELECT MAX(EXTRACTION_DATE) FROM DBCBA.KE_ACCOUNTS_MASTER
    )
    --AND A.ARR_STATUS IN ('CURRENT', 'EXPIRED')
    AND A.PRODUCT_LINE IN ('LENDING')
    /*
    AND (
        CASE
            WHEN A.ACCOUNT_NUMBER = D.ACCOUNT_NUMBER THEN D.EXPOSURE_KES
            ELSE A.ONLINE_ACTUAL_BAL * -1
        END
    ) > 0
    */
    AND A.CATEGORY NOT IN ('3114')
    --AND A.CUSTOMER IN ('488412') --'105351', 106649  '214090', '807100', '491993' '488412', '815096 , '362077'
    AND (CASE
        WHEN A.ACCOUNT_NUMBER = D.ACCOUNT_NUMBER THEN D.EXPOSURE_KES
        ELSE A.ONLINE_ACTUAL_BAL * -1
    END) >0
GROUP BY A.CUSTOMER
),

mobile_loans AS
(
SELECT
	--DISTINCT(A.ACCOUNT_NUMBER) ACCOUNT_NUMBER,
	--CAST(A.ARR_START_DATE AS DATE) ARR_START_DATE,
	DISTINCT(A.CUSTOMER) AS CUSTOMER,
	--A.ARR_PRODUCT_STATUS,
	AVG(A.TERM_AMOUNT) AS AVG_MOB_3
	/*
	(CASE
		WHEN A.ACCOUNT_NUMBER = D.ACCOUNT_NUMBER THEN D.EXPOSURE_KES
		ELSE A.ONLINE_ACTUAL_BAL *-1
	END ) AS EXPOSURE_ACTUAL,
	A.SCHEME_INS_PART,
	A.NIC_SCHEMES,
	CASE WHEN A.SCHEME_INS_PART <>'' then A.SCHEME_INS_PART else A.NIC_SCHEMES end as SCHEME_ID
	*/
	
FROM
	DBCBA.KE_ACCOUNTS_LIST A
LEFT JOIN STGKE.STG_AA_ARREARS C ON
	A.ACCOUNT_NUMBER = C.ACCOUNT_NUMBER
		
LEFT JOIN STGKE.STG_AA_BILL_ARREARS D ON
	A.ARRANGEMENT_ID = D.ARRANGEMENT_ID
		
WHERE
	A.ARR_START_DATE  <= DATEADD(DAY, -(DAY(GETDATE())), CAST(GETDATE() AS DATE))  -- Current day of the month --removes the days of incomplete current month
    AND A.ARR_START_DATE  >= DATEADD(MONTH, -3, DATEADD(DAY, -(DAY(GETDATE()) - 1), CAST(GETDATE() AS DATE)))
	--A.ARR_START_DATE BETWEEN '2024-11-01' AND '2025-01-31'
	AND A.PRODUCT_LINE IN ('LENDING')
	AND A.CATEGORY = '3114'
	AND (CASE
        WHEN A.ACCOUNT_NUMBER = D.ACCOUNT_NUMBER THEN D.EXPOSURE_KES
        ELSE A.ONLINE_ACTUAL_BAL * -1
    END) >0
	--AND A.CUSTOMER IN ('934148')   -- '980481' --'796614' --130219 mobilehigh 618956 886371 581520 '105351', 106649
--ORDER BY ARR_START_DATE ASC

GROUP BY A.CUSTOMER
)

SELECT
	avg_ctos.*,
	ROUND(COALESCE(MB.AVG_MOB_3,0)+COALESCE(TL.SUM_EXPOSURE_ACTUAL,0),2) AS TOTAL_LOANS,
	ROUND((COALESCE(MB.AVG_MOB_3, 0) + COALESCE(TL.SUM_EXPOSURE_ACTUAL, 0)) / avg_income, 2) AS loan_income_ratio
	
	
FROM avg_ctos
LEFT JOIN mobile_loans MB
ON avg_ctos.CUSTOMER_ID = MB.CUSTOMER
LEFT JOIN term_loans TL
ON avg_ctos.CUSTOMER_ID = TL.CUSTOMER