WITH SnapshotDates AS (
    SELECT DISTINCT EXTRACTION_DATE AS SNAPSHOT_DATE
    FROM dbcba.KE_Accounts_Master
    WHERE EXTRACTION_DATE IN (
        '2025-06-30','2025-07-31','2025-08-31',
        '2025-09-30','2025-10-31','2025-11-30'
    )
),

FilteredCustomers AS (
    SELECT am.CUSTOMER
    FROM dbcba.KE_Accounts_List am
    LEFT JOIN dbcba.KE_Customer_Master cm
        ON cm.CUSTOMER_NUMBER = am.CUSTOMER
    WHERE am.PRODUCT_LINE='LENDING'
      AND am.ARR_STATUS='CURRENT'
      AND cm.BUSINESS_SEGMENT IN ('270','250')
      AND COALESCE(am.ONLINE_ACTUAL_BAL,0) < 0
      AND am.CUSTOMER IS NOT NULL
),
                                    
/* ==========================================
   Base Credit Transactions (12M Rolling)
   ========================================== */

BaseCredits AS (
    SELECT
        s.SNAPSHOT_DATE,
        t.CUSTOMER_ID,
        t.BOOKING_DATE,
        CAST(t.AMOUNT_LCY AS DECIMAL(18,2)) AS AMOUNT_LCY
    FROM SnapshotDates s
    JOIN dbcba.KE_ACCOUNT_TRANSACTIONS t
        ON t.BOOKING_DATE <= s.SNAPSHOT_DATE
       AND t.BOOKING_DATE > DATEADD(MONTH,-12,s.SNAPSHOT_DATE)

    WHERE t.AMOUNT_LCY > 0
      AND t.REVERSAL_MARKER <> 'R'
    AND t.CUSTOMER_ID IS NOT NULL
      AND (t.DEBIT_CUSTOMER <> t.CREDIT_CUSTOMER OR t.DEBIT_CUSTOMER IS NULL)
      AND t.SYSTEM_ID NOT IN ('AA')
      AND t.TRANSACTION_CODE NOT IN (
            '1001','944','945','1085','766','949','991','941',
            '433','1006','85','234','859','940','992',
            '947','939','946','948','938','967'
      )
                   and t.CUSTOMER_ID IN (SELECT CUSTOMER FROM FilteredCustomers)
),

/* ==========================================
   Month-Level Aggregation
   ========================================== */

Monthly AS (

SELECT
    SNAPSHOT_DATE,
    CUSTOMER_ID,

    /* Amount Buckets */
    SUM(CASE WHEN DATEDIFF(MONTH, BOOKING_DATE, SNAPSHOT_DATE)=0  THEN AMOUNT_LCY ELSE 0 END) AS M1,
    SUM(CASE WHEN DATEDIFF(MONTH, BOOKING_DATE, SNAPSHOT_DATE)=1  THEN AMOUNT_LCY ELSE 0 END) AS M2,
    SUM(CASE WHEN DATEDIFF(MONTH, BOOKING_DATE, SNAPSHOT_DATE)=2  THEN AMOUNT_LCY ELSE 0 END) AS M3,
    SUM(CASE WHEN DATEDIFF(MONTH, BOOKING_DATE, SNAPSHOT_DATE)=3  THEN AMOUNT_LCY ELSE 0 END) AS M4,
    SUM(CASE WHEN DATEDIFF(MONTH, BOOKING_DATE, SNAPSHOT_DATE)=4  THEN AMOUNT_LCY ELSE 0 END) AS M5,
    SUM(CASE WHEN DATEDIFF(MONTH, BOOKING_DATE, SNAPSHOT_DATE)=5  THEN AMOUNT_LCY ELSE 0 END) AS M6,
    SUM(CASE WHEN DATEDIFF(MONTH, BOOKING_DATE, SNAPSHOT_DATE)=6  THEN AMOUNT_LCY ELSE 0 END) AS M7,
    SUM(CASE WHEN DATEDIFF(MONTH, BOOKING_DATE, SNAPSHOT_DATE)=7  THEN AMOUNT_LCY ELSE 0 END) AS M8,
    SUM(CASE WHEN DATEDIFF(MONTH, BOOKING_DATE, SNAPSHOT_DATE)=8  THEN AMOUNT_LCY ELSE 0 END) AS M9,
    SUM(CASE WHEN DATEDIFF(MONTH, BOOKING_DATE, SNAPSHOT_DATE)=9  THEN AMOUNT_LCY ELSE 0 END) AS M10,
    SUM(CASE WHEN DATEDIFF(MONTH, BOOKING_DATE, SNAPSHOT_DATE)=10 THEN AMOUNT_LCY ELSE 0 END) AS M11,
    SUM(CASE WHEN DATEDIFF(MONTH, BOOKING_DATE, SNAPSHOT_DATE)=11 THEN AMOUNT_LCY ELSE 0 END) AS M12,

    /* Count Buckets */
    COUNT(CASE WHEN DATEDIFF(MONTH, BOOKING_DATE, SNAPSHOT_DATE)=0  THEN 1 END) AS C1,
    COUNT(CASE WHEN DATEDIFF(MONTH, BOOKING_DATE, SNAPSHOT_DATE)=1  THEN 1 END) AS C2,
    COUNT(CASE WHEN DATEDIFF(MONTH, BOOKING_DATE, SNAPSHOT_DATE)=2  THEN 1 END) AS C3,
    COUNT(CASE WHEN DATEDIFF(MONTH, BOOKING_DATE, SNAPSHOT_DATE)=3  THEN 1 END) AS C4,
    COUNT(CASE WHEN DATEDIFF(MONTH, BOOKING_DATE, SNAPSHOT_DATE)=4  THEN 1 END) AS C5,
    COUNT(CASE WHEN DATEDIFF(MONTH, BOOKING_DATE, SNAPSHOT_DATE)=5  THEN 1 END) AS C6,
    COUNT(CASE WHEN DATEDIFF(MONTH, BOOKING_DATE, SNAPSHOT_DATE)=6  THEN 1 END) AS C7,
    COUNT(CASE WHEN DATEDIFF(MONTH, BOOKING_DATE, SNAPSHOT_DATE)=7  THEN 1 END) AS C8,
    COUNT(CASE WHEN DATEDIFF(MONTH, BOOKING_DATE, SNAPSHOT_DATE)=8  THEN 1 END) AS C9,
    COUNT(CASE WHEN DATEDIFF(MONTH, BOOKING_DATE, SNAPSHOT_DATE)=9  THEN 1 END) AS C10,
    COUNT(CASE WHEN DATEDIFF(MONTH, BOOKING_DATE, SNAPSHOT_DATE)=10 THEN 1 END) AS C11,
    COUNT(CASE WHEN DATEDIFF(MONTH, BOOKING_DATE, SNAPSHOT_DATE)=11 THEN 1 END) AS C12

FROM BaseCredits
GROUP BY SNAPSHOT_DATE, CUSTOMER_ID
)

/* ==========================================
   Final Output With Trends
   ========================================== */

SELECT
    SNAPSHOT_DATE,
    CUSTOMER_ID,

    /* Quarter Totals */
    (M1+M2+M3)   AS Q1_CTO,
    (M4+M5+M6)   AS Q2_CTO,
    (M7+M8+M9)   AS Q3_CTO,
    (M10+M11+M12) AS Q4_CTO,

    (C1+C2+C3)   AS Q1_CTO_Count,
    (C4+C5+C6)   AS Q2_CTO_Count,
    (C7+C8+C9)   AS Q3_CTO_Count,
    (C10+C11+C12) AS Q4_CTO_Count,

    /* Month-to-Month Amount Trends */
    CASE WHEN M2=0 THEN NULL ELSE ROUND((M1-M2)/NULLIF(M2,0),2) END AS M1M2_CTO_Amt_Change,
    CASE WHEN M3=0 THEN NULL ELSE ROUND((M2-M3)/NULLIF(M3,0),2) END AS M2M3_CTO_Amt_Change,
    CASE WHEN M4=0 THEN NULL ELSE ROUND((M3-M4)/NULLIF(M4,0),2) END AS M3M4_CTO_Amt_Change,
    CASE WHEN M5=0 THEN NULL ELSE ROUND((M4-M5)/NULLIF(M5,0),2) END AS M4M5_CTO_Amt_Change,
    CASE WHEN M6=0 THEN NULL ELSE ROUND((M5-M6)/NULLIF(M6,0),2) END AS M5M6_CTO_Amt_Change,
    CASE WHEN M7=0 THEN NULL ELSE ROUND((M6-M7)/NULLIF(M7,0),2) END AS M6M7_CTO_Amt_Change,
    CASE WHEN M8=0 THEN NULL ELSE ROUND((M7-M8)/NULLIF(M8,0),2) END AS M7M8_CTO_Amt_Change,
    CASE WHEN M9=0 THEN NULL ELSE ROUND((M8-M9)/NULLIF(M9,0),2) END AS M8M9_CTO_Amt_Change,
    CASE WHEN M10=0 THEN NULL ELSE ROUND((M9-M10)/NULLIF(M10,0),2) END AS M9M10_CTO_Amt_Change,
    CASE WHEN M11=0 THEN NULL ELSE ROUND((M10-M11)/NULLIF(M11,0),2) END AS M10M11_CTO_Amt_Change,
    CASE WHEN M12=0 THEN NULL ELSE ROUND((M11-M12)/NULLIF(M12,0),2) END AS M11M12_CTO_Amt_Change,

    /* Quarter-to-Quarter Amount Trends */
    CASE WHEN (M4+M5+M6)=0 THEN NULL
         ELSE ROUND(((M1+M2+M3)-(M4+M5+M6)) / NULLIF((M4+M5+M6),0),2)
    END AS Q1Q2_CTO_Amt_Change,

    CASE WHEN (M7+M8+M9)=0 THEN NULL
         ELSE ROUND(((M4+M5+M6)-(M7+M8+M9)) / NULLIF((M7+M8+M9),0),2)
    END AS Q2Q3_CTO_Amt_Change,

    CASE WHEN (M10+M11+M12)=0 THEN NULL
         ELSE ROUND(((M7+M8+M9)-(M10+M11+M12)) / NULLIF((M10+M11+M12),0),2)
    END AS Q3Q4_CTO_Amt_Change

FROM Monthly
ORDER BY SNAPSHOT_DATE, CUSTOMER_ID;