WITH DPDS 
AS
(
select [CUSTOMER NO], MAX([EXCESS DAYS]) AS MAX_DPDs
FROM
STGKE.STG_AA_DAYS_EXCESS 
WHERE EXTRACTION_DATE = (SELECT MAX(PROCESSING_DATE) FROM DBCBA.end_of_day)
GROUP BY [CUSTOMER NO]
UNION
select [CUSTOMER], MAX([OD_DAYS]) 
FROM 
STGKE.STG_AA_BILL_ARREARS 
WHERE EXTRACTION_DATE = (SELECT MAX(PROCESSING_DATE) FROM DBCBA.end_of_day)
GROUP BY [CUSTOMER]
)
SELECT [CUSTOMER NO] , max(MAX_DPDs)
FROM DPDS
group by [CUSTOMER NO]