SELECT DISTINCT CUSTOMER_NUMBER,CUS_SHORT_NAME,
ACCOUNT_OFFICER_NAME,BUSINESS_SEGMENT_DESC,CUSTOMER_BRANCH_NAME ,EMPLOYERS_NAME,CUST_MOB_PHONE,OFF_PHONE,SMS_1,PHONE_1,CUST_EMAIL_ID
FROM
DBCBA.KE_Customer_Master 
WHERE EXTRACTION_DATE =(select max(processing_date) from dbcba.end_of_day) --AND 
--(UPPER(EMPLOYERS_NAME) LIKE 'KQ' OR
--UPPER(EMPLOYERS_NAME) LIKE '%KENYA AIRWAYS%' OR
--UPPER(EMPLOYERS_NAME) LIKE '%KENYA AIRWAY%' OR
--UPPER(EMPLOYERS_NAME) LIKE '%KQ LTD%' OR
--UPPER(EMPLOYERS_NAME) LIKE '%KQ Group%' OR
--UPPER(EMPLOYERS_NAME) LIKE 'KQ %')
--and CLASSIFICATION in ('A1','A2','A3','A4','A5')


SELECT DISTINCT CUSTOMER_NUMBER,CUS_SHORT_NAME,
ACCOUNT_OFFICER_NAME,BUSINESS_SEGMENT_DESC,CUSTOMER_BRANCH_NAME ,EMPLOYERS_NAME,CUST_MOB_PHONE,OFF_PHONE,SMS_1,PHONE_1,CUST_EMAIL_ID
FROM
DBCBA.KE_Customer_Master 
WHERE EXTRACTION_DATE =(select max(processing_date) from dbcba.end_of_day) AND 
 UPPER(CUS_SHORT_NAME) LIKE UPPER('%Muranga Wholesalers%')
    OR UPPER(CUS_SHORT_NAME) LIKE UPPER('%Ishano distributors%')
    OR UPPER(CUS_SHORT_NAME) LIKE UPPER('%Delta Point%')
    OR UPPER(CUS_SHORT_NAME) LIKE UPPER('%Kinginya & Sons%')
    OR UPPER(CUS_SHORT_NAME) LIKE UPPER('%Mt. Kenya beer/Karue%')
    OR UPPER(CUS_SHORT_NAME) LIKE UPPER('%Capwell Industries%')
    OR UPPER(CUS_SHORT_NAME) LIKE UPPER('%Vivo Energy%')
    OR UPPER(CUS_SHORT_NAME) LIKE UPPER('%Brookside Dairy%')

