With AA_Collateral_Unions as
(
				SELECT ID_COMP_1 AS AA_AARANGEMENT, COLLAT_ID AS AA__COLLAT_ID
				FROM STGKE.STG_AA_ARR_OFFICERS
				WHERE COLLAT_ID IS NOT NULL
				UNION ALL
				SELECT ID_COMP_1 AS AA_AARANGEMENT, COLLAT_ID1 AS AA__COLLAT_ID
				FROM STGKE.STG_AA_ARR_OFFICERS
				WHERE COLLAT_ID1 IS NOT NULL
				UNION ALL
				SELECT ID_COMP_1 AS AA_AARANGEMENT, COLLAT_ID2 AS AA__COLLAT_ID
				FROM STGKE.STG_AA_ARR_OFFICERS
				WHERE COLLAT_ID2 IS NOT NULL
				UNION ALL
				SELECT ID_COMP_1 AS AA_AARANGEMENT, COLLAT_ID3 AS AA__COLLAT_ID
				FROM STGKE.STG_AA_ARR_OFFICERS
				WHERE COLLAT_ID3 IS NOT NULL
				UNION ALL
				SELECT ID_COMP_1 AS AA_AARANGEMENT, COLLAT_ID4 AS AA__COLLAT_ID
				FROM STGKE.STG_AA_ARR_OFFICERS
				WHERE COLLAT_ID4 IS NOT NULL
				UNION ALL
				SELECT ID_COMP_1 AS AA_AARANGEMENT, COLLAT_ID5 AS AA__COLLAT_ID
				FROM STGKE.STG_AA_ARR_OFFICERS
				WHERE COLLAT_ID5 IS NOT NULL
				UNION ALL
				SELECT ID_COMP_1 AS AA_AARANGEMENT, COLLAT_ID6 AS AA__COLLAT_ID
				FROM STGKE.STG_AA_ARR_OFFICERS
				WHERE COLLAT_ID6 IS NOT NULL
				UNION ALL
				SELECT ID_COMP_1 AS AA_AARANGEMENT, COLLAT_ID7 AS AA__COLLAT_ID
				FROM STGKE.STG_AA_ARR_OFFICERS
				WHERE COLLAT_ID7 IS NOT NULL
				UNION ALL
				SELECT ID_COMP_1 AS AA_AARANGEMENT, COLLAT_ID8 AS AA__COLLAT_ID
				FROM STGKE.STG_AA_ARR_OFFICERS
				WHERE COLLAT_ID8 IS NOT NULL
				UNION ALL
				SELECT ID_COMP_1 AS AA_AARANGEMENT, COLLAT_ID9 AS AA__COLLAT_ID
				FROM STGKE.STG_AA_ARR_OFFICERS
				WHERE COLLAT_ID9 IS NOT NULL
				UNION ALL
				SELECT ID_COMP_1 AS AA_AARANGEMENT, COLLAT_ID10 AS AA__COLLAT_ID
				FROM STGKE.STG_AA_ARR_OFFICERS
				WHERE COLLAT_ID10 IS NOT NULL
),
AA_CID_Merge AS 
(
select 
acu.AA__COLLAT_ID,acu.AA_AARANGEMENT as [AA_AARANGEMENT_ATTACHED],cm.CUSTOMER_NUMBER,cm.CUS_SHORT_NAME, c.COLLATERAL_TYPE,dt.COLLATERAL_TYPE_DESCRIPTION,c.DESCRIPTION,c.DESCRIPTION_1,
c.CURRENCY,c.EXECUTION_VALUE ,c.NOMINAL_VALUE [MARKET VALUE],c.MAXIMUM_VALUE [CHARGED AMOUNT],ad.VEHICLE_MODEL, ad.REG_NUMBER,ad.INSURANCE_TYPE,ad.INSURANCE_AMT,
			CASE 
			    WHEN ISDATE(TRIM(ad.INSUR_EXP_DATE)) = 1 THEN CAST(TRIM(ad.INSUR_EXP_DATE) AS DATE)
			    ELSE NULL
			END AS INSUR_EXP_DATE,
			CASE 
			    WHEN ISDATE(TRIM(ad.VAL_EXPIRY_DATE)) = 1 THEN CAST(TRIM(ad.VAL_EXPIRY_DATE) AS DATE)
			    ELSE NULL
			END AS VAL_EXPIRY_DATE,
ad.MARKET_VALUE,ad.FORCE_VALUE,cm.BUSINESS_SEGMENT, cm.SUB_SEGEMENT, cm.SUB_SEGEMENT_DESC,
 cm.CUSTOMER_BRANCH_NAME,cm.ACCOUNT_OFFICER_NAME ,cm.CUS_ACC_OFFICER ,am.ARR_STATUS AS LOAN_STATUS
FROM AA_Collateral_Unions acu
	inner join stgke.STG_Collateral c
	on acu.AA__COLLAT_ID=c.RECID
	INNER JOIN stgke.STG_NIC_CO_ADDL_DETS ad
	on acu.AA__COLLAT_ID=ad.RECID
	left join dbcba.collateral_type dt 
	on c.COLLATERAL_TYPE=dt.COLLATERAL_TYPE
	inner join dbcba.KE_Accounts_Master am
	on acu.AA_AARANGEMENT=am.ARRANGEMENT_ID 
	inner join dbcba.KE_Customer_Master cm
	on am.CUSTOMER =cm.CUSTOMER_NUMBER and am.EXTRACTION_DATE=cm.EXTRACTION_DATE
where cm.EXTRACTION_DATE =(select max(processing_date) from dbcba.end_of_day)
and am.PRODUCT_LINE ='LENDING' AND am.ARR_STATUS in ('CURRENT','EXPIRED') and cm.BUSINESS_SEGMENT in ('270','250','200')
and cm.CLASSIFICATION <>'B20'
and c.COLLATERAL_TYPE in ('101',	'152',	'151',	'103',	'102',	'104',	'301',	'621',	'143',	'311',	'107',	'157',	'111',	'153',	'308',	'540',	'802',	'105',	'109',	'121',	'155',	'159',	'302',	'306',	'310',	'313',	'520',	'611',	'631',	'804',	'106',	'108',	'110',	'120',	'154',	'156',	'158',	'280',	'303',	'305',	'307',	'309',	'312',	'314',	'502',	'504',	'530',	'630',	'911',	'922',	'241')
),
COVENANT_STATUS AS
(
select 
case 
	when COLLATERAL_TYPE in ('109','101','103',	'104',	'107',	'105',	'109',	'159',	'106',	'108') then 'NOT APPLICABLE'
	when (INSUR_EXP_DATE IS NULL OR INSUR_EXP_DATE < CURRENT_TIMESTAMP) then 'EXPIRED'
	else 'CURRENT'
end AS [INSURANCE STATUS],
case 
	
	when  COLLATERAL_TYPE not in ('101',	'152',	'151',	'103',	'102',	'104', '107',	'157',	
	'153',	'105',	'109',	'155',	'159',	'611',	'631',	'106',	'108',	'154',	
	'156',	'158',	'630') then 'NOT APPLICABLE'
	when (VAL_EXPIRY_DATE IS NULL OR VAL_EXPIRY_DATE < CURRENT_TIMESTAMP ) then 'EXPIRED'
	else 'CURRENT'
end AS [VALUATION STATUS],
*
from AA_CID_Merge
)
select *
from COVENANT_STATUS
where ([INSURANCE STATUS]='EXPIRED' OR [VALUATION STATUS]='EXPIRED')
--where CUSTOMER_NUMBER<>'118326'
--AND COLLATERAL_TYPE='102'







