With AA_Collateral_Unions as
(
				SELECT ID_COMP_1 AS AA_ARRANGEMENT, COLLAT_ID AS AA__COLLAT_ID
				FROM STGKE.STG_AA_ARR_OFFICERS
				WHERE COLLAT_ID IS NOT NULL
				UNION ALL
				SELECT ID_COMP_1 AS AA_ARRANGEMENT, COLLAT_ID1 AS AA__COLLAT_ID
				FROM STGKE.STG_AA_ARR_OFFICERS
				WHERE COLLAT_ID1 IS NOT NULL
				UNION ALL
				SELECT ID_COMP_1 AS AA_ARRANGEMENT, COLLAT_ID2 AS AA__COLLAT_ID
				FROM STGKE.STG_AA_ARR_OFFICERS
				WHERE COLLAT_ID2 IS NOT NULL
				UNION ALL
				SELECT ID_COMP_1 AS AA_ARRANGEMENT, COLLAT_ID3 AS AA__COLLAT_ID
				FROM STGKE.STG_AA_ARR_OFFICERS
				WHERE COLLAT_ID3 IS NOT NULL
				UNION ALL
				SELECT ID_COMP_1 AS AA_ARRANGEMENT, COLLAT_ID4 AS AA__COLLAT_ID
				FROM STGKE.STG_AA_ARR_OFFICERS
				WHERE COLLAT_ID4 IS NOT NULL
				UNION ALL
				SELECT ID_COMP_1 AS AA_ARRANGEMENT, COLLAT_ID5 AS AA__COLLAT_ID
				FROM STGKE.STG_AA_ARR_OFFICERS
				WHERE COLLAT_ID5 IS NOT NULL
				UNION ALL
				SELECT ID_COMP_1 AS AA_ARRANGEMENT, COLLAT_ID6 AS AA__COLLAT_ID
				FROM STGKE.STG_AA_ARR_OFFICERS
				WHERE COLLAT_ID6 IS NOT NULL
				UNION ALL
				SELECT ID_COMP_1 AS AA_ARRANGEMENT, COLLAT_ID7 AS AA__COLLAT_ID
				FROM STGKE.STG_AA_ARR_OFFICERS
				WHERE COLLAT_ID7 IS NOT NULL
				UNION ALL
				SELECT ID_COMP_1 AS AA_ARRANGEMENT, COLLAT_ID8 AS AA__COLLAT_ID
				FROM STGKE.STG_AA_ARR_OFFICERS
				WHERE COLLAT_ID8 IS NOT NULL
				UNION ALL
				SELECT ID_COMP_1 AS AA_ARRANGEMENT, COLLAT_ID9 AS AA__COLLAT_ID
				FROM STGKE.STG_AA_ARR_OFFICERS
				WHERE COLLAT_ID9 IS NOT NULL
				UNION ALL
				SELECT ID_COMP_1 AS AA_ARRANGEMENT, COLLAT_ID10 AS AA__COLLAT_ID
				FROM STGKE.STG_AA_ARR_OFFICERS
				WHERE COLLAT_ID10 IS NOT NULL
),
AA_CID_Merge AS 
(
select 
ad.RECID as COLLATERAL_ID,dt.COLLATERAL_TYPE_DESCRIPTION,acu.CUSTOMER,cm.CUS_SHORT_NAME,acu.ARRANGEMENT_ID,acu.CURRENCY as LOAN_CURRENCY,
((CONVERT(DECIMAL(18,0),acu.ONLINE_ACTUAL_BAL)*acu.EXCHANGE_RATE)*-1) as PRINCIPAL_BAL_KES,
(CONVERT(DECIMAL(18,0),(COALESCE (dpd.ARREARS_AMOUNT ,0)) )*acu.EXCHANGE_RATE) AS ARREARS_KES, COALESCE (dpd.Days_In_Arrears ,0) as OD_DAYS,
c.COLLATERAL_TYPE,c.DESCRIPTION,c.DESCRIPTION_1,
c.CURRENCY AS COLLATERAL_VALUE_CURRENCY,c.EXECUTION_VALUE ,c.NOMINAL_VALUE [MARKET VALUE],c.MAXIMUM_VALUE [CHARGED AMOUNT],ad.VEHICLE_MODEL, ad.REG_NUMBER,ad.INSURANCE_TYPE,ad.INSURANCE_AMT,
			CASE 
			    WHEN ISDATE(TRIM(ad.INSUR_EXP_DATE)) = 1 THEN CAST(TRIM(ad.INSUR_EXP_DATE) AS DATE)
			    ELSE NULL
			END AS INSUR_EXP_DATE,
			CASE 
			    WHEN ISDATE(TRIM(ad.VAL_EXPIRY_DATE)) = 1 THEN CAST(TRIM(ad.VAL_EXPIRY_DATE) AS DATE)
			    ELSE NULL
			END AS VAL_EXPIRY_DATE,
ad.MARKET_VALUE,ad.FORCE_VALUE
FROM stgke.STG_Collateral c
			inner join 	(SELECT DISTINCT AA__COLLAT_ID, pdo.CUSTOMER,pdo.CURRENCY ,pdo.ARRANGEMENT_ID,pdo.ONLINE_ACTUAL_BAL,pdo.EXCHANGE_RATE FROM AA_Collateral_Unions cu
						inner join dbcba.KE_Accounts_List pdo
						on cu.AA_ARRANGEMENT=pdo.ARRANGEMENT_ID where
						pdo.PRODUCT_LINE ='LENDING' AND 
						pdo.ARR_STATUS in ('CURRENT','EXPIRED') AND pdo.ONLINE_ACTUAL_BAL <0 ) acu
			on acu.AA__COLLAT_ID=c.RECID	
			INNER JOIN stgke.STG_NIC_CO_ADDL_DETS ad
			on acu.AA__COLLAT_ID=ad.RECID
			left join dbcba.collateral_type dt 
			on c.COLLATERAL_TYPE=dt.COLLATERAL_TYPE
			LEFT join dbcba.KE_Customer_Master cm
			on acu.CUSTOMER =cm.CUSTOMER_NUMBER and cm.EXTRACTION_DATE =(select max(processing_date) from dbcba.end_of_day)
			left join STGKE.STG_AA_ARREARS dpd
		on acu.ARRANGEMENT_ID = dpd.ARRANGEMENT_ID and dpd.EXTRACTION_DATE =(select max(processing_date) from dbcba.end_of_day)
where cm.BUSINESS_SEGMENT in ('270','250','200')
and cm.CLASSIFICATION <>'B20'
and c.COLLATERAL_TYPE in ('101','152',	'151',	'103',	'102',	'104',	'301',	'621',	'143',	'311',	'107',	
'157',	'111',	'153',	'308',	'540',	'802',	'105',	'109',	'121',	'155',	'159',	'302',	'306',	'310',	'313',	'520',
'611',	'631',	'804',	'106',	'108',	'110',	'120',	'154',	'156',	'158',	'280',	'303',	'305',	'307',	'309',	'312',	'314',	
'502',	'504',	'530',	'630',	'911',	'922',	'241', '931', '911','921','922')
),
COVENANT_STATUS AS
(
select 
case 
	when COLLATERAL_TYPE in ('109','101','103',	'104',	'107',	'105',	'109',	'159',	'106',	'108') then 'NOT APPLICABLE'
	when (INSUR_EXP_DATE IS NULL OR INSUR_EXP_DATE < CURRENT_TIMESTAMP) then 'EXPIRED'
	else 'CURRENT'
end AS [INSURANCE STATUS],
case 
		when  COLLATERAL_TYPE not in ('101',	'152',	'151',	'103',	'102',	'104', '107',	'157',	
	'153',	'105',	'109',	'155',	'159',	'611',	'631',	'106',	'108',	'154',	
	'156',	'158',	'630') then 'NOT APPLICABLE'
	when (VAL_EXPIRY_DATE IS NULL OR VAL_EXPIRY_DATE < CURRENT_TIMESTAMP ) then 'EXPIRED'
	else 'CURRENT'
end AS [VALUATION STATUS],
CASE 
	WHEN COLLATERAL_TYPE IN ('931','911','921','922') THEN 'Life Cover'
	else 'Others'
END 'LIFE COVERS',
*
from AA_CID_Merge
)
select *
from COVENANT_STATUS
--where --([INSURANCE STATUS]='EXPIRED' OR [VALUATION STATUS]='EXPIRED') 
--AND COLLATERAL_TYPE IN ('931','911','921','922')      --LIFE COVERS
--CUSTOMER in ('534364'),
where [VALUATION STATUS]<> 'NOT APPLICABLE'
ORDER BY CUSTOMER



