---first installment default
WITH T1 AS 
(
SELECT 
	A.customer_number,
	A.ACCOUNT_NUMBER,
	A.EXTRACTION_DATE,
	B.ARR_START_DATE,
	A.ARREARS_DATE,
	B.MATURITY_DATE,
	A.Days_In_Arrears,
	DATEDIFF(DAY,B.ARR_START_DATE, A.ARREARS_DATE) AS disb_arr_diff_days,
	
	CASE
		WHEN DATEDIFF(DAY,B.ARR_START_DATE, A.ARREARS_DATE) BETWEEN 1 AND 30 THEN 'Y' ELSE 'N'
	END AS disb_arr_status
		

FROM STGKE.STG_AA_ARREARS A
LEFT JOIN DBCBA.KE_ACCOUNTS_LIST B
ON 
A.ACCOUNT_NUMBER = B.ACCOUNT_NUMBER

WHERE 
A.EXTRACTION_DATE BETWEEN DATEADD(DAY, -365, GETDATE()-1) AND GETDATE()-1
--AND B.CATEGORY NOT IN ('3729', '3730', '3731')
AND A.Days_In_Arrears IS NOT NULL
AND B.ARR_START_DATE IS NOT NULL
AND A.customer_number IS NOT NULL
AND Days_In_Arrears BETWEEN 1 AND 30
AND (CASE
		WHEN DATEDIFF(DAY,B.ARR_START_DATE, A.ARREARS_DATE) BETWEEN 1 AND 30 THEN 'Y' ELSE 'N'
	END) = 'Y'
--ORDER BY disb_arr_diff_days ASC

)
,
FIDs AS 
(
SELECT
	DISTINCT(ACCOUNT_NUMBER) AS ACCOUNT_NUMBER,
	MIN(EXTRACTION_DATE) AS EXTRACTION_DATE,
	customer_number,
	ARR_START_DATE,
	ARREARS_DATE,
	MATURITY_DATE,
	Days_In_Arrears,
	disb_arr_status


FROM T1
WHERE disb_arr_status = 'Y'
AND Days_In_Arrears = 1
GROUP BY ACCOUNT_NUMBER, customer_number, ARREARS_DATE,	MATURITY_DATE,
	Days_In_Arrears, disb_arr_status, ARR_START_DATE
ORDER BY customer_number ASC, EXTRACTION_DATE ASC
)
SELECT 
	customer_number,
	COUNT(ACCOUNT_NUMBER) AS no_of_accounts_fid

FROM FIDs
GROUP BY customer_number
ORDER BY no_of_accounts_fid DESC  