with CTOs as
(SELECT 
    tran.ACCOUNT_NUMBER, cm.CUSTOMER_NUMBER , CM.CUS_SHORT_NAME,al.CATEGORY,al.CATEGORY_DESC,
    --SUM(CASE WHEN MONTH(tran.BOOKING_DATE) = 1 AND YEAR(tran.BOOKING_DATE) = 2025 THEN tran.AMOUNT_LCY ELSE 0 END) AS 'January_2025',
   -- SUM(CASE WHEN MONTH(tran.BOOKING_DATE) = 2 AND YEAR(tran.BOOKING_DATE) = 2025 THEN tran.AMOUNT_LCY ELSE 0 END) AS 'February_2025',
    --SUM(CASE WHEN MONTH(tran.BOOKING_DATE) = 3 AND YEAR(tran.BOOKING_DATE) = 2025 THEN tran.AMOUNT_LCY ELSE 0 END) AS 'March_2025',
    --SUM(CASE WHEN MONTH(tran.BOOKING_DATE) = 4 AND YEAR(tran.BOOKING_DATE) = 2025 THEN tran.AMOUNT_LCY ELSE 0 END) AS 'April_2025',
   -- SUM(CASE WHEN MONTH(tran.BOOKING_DATE) = 5 AND YEAR(tran.BOOKING_DATE) = 2025 THEN tran.AMOUNT_LCY ELSE 0 END) AS 'May_2025',
    --SUM(CASE WHEN MONTH(tran.BOOKING_DATE) = 6 AND YEAR(tran.BOOKING_DATE) = 2025 THEN tran.AMOUNT_LCY ELSE 0 END) AS 'June_2025',
   -- SUM(CASE WHEN MONTH(tran.BOOKING_DATE) = 7 AND YEAR(tran.BOOKING_DATE) = 2025 THEN tran.AMOUNT_LCY ELSE 0 END) AS 'July_2025',
    --SUM(CASE WHEN MONTH(tran.BOOKING_DATE) = 8 AND YEAR(tran.BOOKING_DATE) = 2025 THEN tran.AMOUNT_LCY ELSE 0 END) AS 'August_2025',
    -- SUM(CASE WHEN MONTH(tran.BOOKING_DATE) = 9 AND YEAR(tran.BOOKING_DATE) = 2025 THEN tran.AMOUNT_LCY ELSE 0 END) AS 'September_2025',
      --SUM(CASE WHEN MONTH(tran.BOOKING_DATE) = 10 AND YEAR(tran.BOOKING_DATE) = 2025 THEN tran.AMOUNT_LCY ELSE 0 END) AS 'October_2025',
   --   SUM(CASE WHEN MONTH(tran.BOOKING_DATE) = 11 AND YEAR(tran.BOOKING_DATE) = 2025 THEN tran.AMOUNT_LCY ELSE 0 END) AS 'November_2025',
    --  SUM(CASE WHEN MONTH(tran.BOOKING_DATE) = 12 AND YEAR(tran.BOOKING_DATE) = 2025 THEN tran.AMOUNT_LCY ELSE 0 END) AS 'Decemeber_2025',
     -- SUM(CASE WHEN MONTH(tran.BOOKING_DATE) = 1 AND YEAR(tran.BOOKING_DATE) = 2026 THEN tran.AMOUNT_LCY ELSE 0 END) AS 'January_2026',
      SUM(CASE WHEN MONTH(tran.BOOKING_DATE) = 2 AND YEAR(tran.BOOKING_DATE) = 2026 THEN tran.AMOUNT_LCY ELSE 0 END) AS 'February_2026',
      SUM(CASE WHEN MONTH(tran.BOOKING_DATE) = 3 AND YEAR(tran.BOOKING_DATE) = 2026 THEN tran.AMOUNT_LCY ELSE 0 END) AS 'March_2026',
           SUM(CASE WHEN MONTH(tran.BOOKING_DATE) = 4 AND YEAR(tran.BOOKING_DATE) = 2026 THEN tran.AMOUNT_LCY ELSE 0 END) AS 'April_2026'
FROM 
    dbcba.KE_ACCOUNT_TRANSACTIONS AS tran
    inner join (select * from dbcba.KE_Customer_Master where EXTRACTION_DATE = (select max(processing_date) from dbcba.end_of_day)) cm
    on tran.CUSTOMER_ID = cm.CUSTOMER_NUMBER 
    left join (select ACCOUNT_NUMBER,CATEGORY_DESC,CATEGORY,PRODUCT_LINE FROM dbcba.KE_Accounts_List where PRODUCT_LINE ='ACCOUNTS') al
    on tran.ACCOUNT_NUMBER = al.ACCOUNT_NUMBER
WHERE 
   tran.AMOUNT_LCY > 0 
    AND txn_code_initiation ='CUSTOMER' 
 and (tran.CREDIT_CUSTOMER <> tran.DEBIT_CUSTOMER 
     OR (tran.CREDIT_CUSTOMER IS NULL OR tran.CREDIT_CUSTOMER = '')
     OR (tran.DEBIT_CUSTOMER IS NULL OR tran.DEBIT_CUSTOMER = ''))
and (tran.CUSTOMER_ID <> tran.DEBIT_CUSTOMER 
    OR (tran.CUSTOMER_ID IS NULL OR tran.CUSTOMER_ID = '')
    OR (tran.DEBIT_CUSTOMER IS NULL OR tran.DEBIT_CUSTOMER = ''))
      AND tran.TRANSACTION_CODE NOT IN ('1085', '766', '949', '945', '991', '941', '433', '1006', '85', 
   '234', '859', '940', '992', '947', '939', '946', '944', '948', '938', '1001')
    and tran.REVERSAL_MARKER<>'R'
    and tran.ORDERING_CUST NOT IN ('727119') and PROFIT_CENTRE_CUST NOT IN ('727119') --MMF 
    AND DEPARTMENT_CODE NOT IN ('3976') --& FT
   AND tran.BOOKING_DATE BETWEEN '2025-01-01' AND '2026-12-31'
GROUP BY 
    tran.ACCOUNT_NUMBER,
     cm.CUSTOMER_NUMBER,
    cm.CUS_SHORT_NAME,
    al.CATEGORY,
    al.CATEGORY_DESC)
    select *
    --CONVERT(DECIMAL(20,2),(July_2024+August_2024+September_2024+October_2024+November_2024+December_2024+January_2025+February_2025+March_2025+April_2025+May_2025+June_2025)/12) AS AvgCTOs
    --CONVERT(DECIMAL(20,2),(January_2025+February_2025+March_2025+April_2025+May_2025+June_2025+July_2025+August_2025)/8) AS AvgCTOs
    from CTOs
   WHERE --lower(CATEGORY_DESC) like '%staff%' and lower(CUS_SHORT_NAME) like '%staff%' 
  CUSTOMER_NUMBER = '256992'
   --------------------------------
  
  select BOOKING_DATE,AMOUNT_LCY,txn_code_description,PAYMENT_DETAILS* from
    dbcba.KE_ACCOUNT_TRANSACTIONS 
    where ACCOUNT_NUMBER ='2569920023'
    AND BOOKING_DATE BETWEEN '2025-04-01' AND '2026-12-31'
   
   