with LFALoansDasboard as
 (
select CAST(am.EXTRACTION_DATE AS DATE) as EXTRACTION_DATE ,cm.CUS_SHORT_NAME, am.CUSTOMER,am.ARRANGEMENT_ID,am.ACCOUNT_NUMBER,
case 
	when stl.PAYOUT_ACCOUNT is null or stl.PAYOUT_ACCOUNT='' then stl.PAYIN_ACCOUNT 
	else stl.PAYOUT_ACCOUNT 
end as SETTLEMENT_ACCOUNT,
cm.CLASSIFICATION,am.CATEGORY_DESC,am.CURRENCY,am.INTEREST_RATE,(COALESCE (am.ONLINE_ACTUAL_BAL,0)*-1)/1000 as [ONLINE_ACTUAL_BAL_Kes_000], CONVERT(DECIMAL(18,0),am.TERM_AMOUNT)/1000 as [DISBURSED_AMT_Kes_000], 
CONVERT(DECIMAL(18,0),ex.Deal_balance) as EXPOSURE_ACTUAL, 
case 
	when am.CURRENCY ='KES' then CONVERT(DECIMAL(18,0),ex.Deal_balance)
	else CONVERT(DECIMAL(18,0),ex.Deal_balance)*am.EXCHANGE_RATE
end as EXPOSURE_KES,
CONVERT(DECIMAL(18,0),(COALESCE (pdo.ARREARS_AMOUNT ,0)) ) AS ARREARS_KES, COALESCE (pdo.Days_In_Arrears ,0) as OD_DAYS,
DATE(am.VALUE_DATE) as VALUE_DATE, DATE(am.MATURITY_DATE ) as MATURITY_DATE,DATE(am.PAYMENT_START_DATE) as PAYMENT_START_DATE,
CASE MONTH(am.PAYMENT_START_DATE)
        WHEN 1 THEN 'January'
        WHEN 2 THEN 'February'
        WHEN 3 THEN 'March'
        WHEN 4 THEN 'April'
        WHEN 5 THEN 'May'
        WHEN 6 THEN 'June'
        WHEN 7 THEN 'July'
        WHEN 9 THEN 'September'
        WHEN 8 THEN 'August'
        WHEN 10 THEN 'October'
        WHEN 11 THEN 'November'
        WHEN 12 THEN 'December'
    END + STR(YEAR(am.PAYMENT_START_DATE)) AS [PAYMENT START MONTH],
    CASE MONTH(am.VALUE_DATE)
        WHEN 1 THEN 'January'
        WHEN 2 THEN 'February'
        WHEN 3 THEN 'March'
        WHEN 4 THEN 'April'
        WHEN 5 THEN 'May'
        WHEN 6 THEN 'June'
        WHEN 7 THEN 'July'
        WHEN 8 THEN 'August'
        WHEN 9 THEN 'September'
        WHEN 10 THEN 'October'
        WHEN 11 THEN 'November'
        WHEN 12 THEN 'December'
    END + STR(YEAR(am.VALUE_DATE)) AS [LOAN BOOKING MONTH],
am.REPAYMENT_AMT AS EMI,
DATEDIFF(MONTH,CONVERT(DATE,am.VALUE_DATE),CURRENT_TIMESTAMP) as MOB,
 am.ARR_STATUS AS LOAN_STATUS, 
 CASE
 	when  am.ARR_STATUS IN ('CURRENT','EXPIRED') AND OD_DAYS<31then 'NORMAL'
	when am.ARR_STATUS IN ('CURRENT','EXPIRED') AND OD_DAYS<91 then 'WATCH'
	when am.ARR_STATUS IN ('CURRENT','EXPIRED') AND OD_DAYS>90 then 'NPL'
	ELSE 'CLOSED'
 END AS [LIVE CLASSIFICATIONS], 
 CASE
 	when  am.VALUE_DATE < '2024-07-01' then 'OLD UPLOAD'
 	when  am.VALUE_DATE between '2024-07-01' and '2024-11-20' then 'PILOT UPLOAD'
 	when  am.VALUE_DATE >= '2024-11-21' then 'POST GO LIVE'
 END AS [UPLOAD COHORTS], 
  CASE
 	when  am.ARR_STATUS IN ('CURRENT','EXPIRED') AND OD_DAYS<31then (COALESCE (AM.ONLINE_ACTUAL_BAL,0)*-1)/1000 
		ELSE 0
 END AS [NORMAL PR_BALANCE_Kes_000], 
 CASE
 	when  am.ARR_STATUS IN ('CURRENT','EXPIRED') AND OD_DAYS BETWEEN 31 AND 90 then (COALESCE (AM.ONLINE_ACTUAL_BAL,0)*-1)/1000
		ELSE 0
 END AS [PAR PR_BALANCE_Kes_000], 
 CASE
 	when  am.ARR_STATUS IN ('CURRENT','EXPIRED') AND OD_DAYS>90 then (COALESCE (AM.ONLINE_ACTUAL_BAL,0)*-1)/1000
		ELSE 0
 END AS [NPL PR_BALANCE_Kes_000], 
case 
	when cm.BUSINESS_SEGMENT in ('270','250') then 'CONSUMER BANKING'
	when cm.BUSINESS_SEGMENT in ('200') then 'COMMERCIAL & BUSINESS BANKING'
end as BUSINESS_UNIT,
cm.SUB_SEGEMENT_DESC, cm.CUSTOMER_BRANCH_NAME ,cm.ACCOUNT_OFFICER_NAME,
CASE
	WHEN DATE(am.PAYMENT_START_DATE)<current_timestamp then 'REPAYMENT_STARTED'
	else 'GRACE PERIOD'
END as [REPAYMENT STATUS],
Case
	when OD_DAYS=0 then 'Zero DPD'
	when OD_DAYS <16 then 'DPD_ 1-15'
	when OD_DAYS<31 then 'DPD_16-30'
	when OD_DAYS<46 then 'DPD_31-45'
	when OD_DAYS<61 then 'DPD_46-60'
	when OD_DAYS<75then 'DPD_61-75'
	when OD_DAYS<91 then 'DPD_76-90'
	when OD_DAYS>90 then 'DPD_>90 (NPL)'
END as [OD DAYS SEGMENTS],
Case
	when ARREARS_KES>0 then 'WITH ARREARS'
	ELSE 'NO ARREARS'
	END as [ARRERAS STATUS],
CASE
WHEN cm.CUSTOMER_BRANCH =  '122'   THEN 'ABC BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '213'   THEN 'BUNGOMA BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '133'   THEN 'BURU BURU BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '219'   THEN 'BUSIA BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '1060'   THEN 'CHANGAMWE BRANCH, MOMBASA'
WHEN cm.CUSTOMER_BRANCH =  '1060'   THEN 'CHANGAMWE BRANCH, MOMBASA'
WHEN cm.CUSTOMER_BRANCH =  '220'   THEN 'CHWELE BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '142'   THEN 'CIATA MALL BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '101'   THEN 'CITY CENTRE BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '108'   THEN 'CITY MALL BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '108'   THEN 'CITY MALL BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '108'   THEN 'CITY MALL BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '700'   THEN 'DIANI BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '700'   THEN 'DIANI BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '221'   THEN 'EASTLEIGH BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '1320'   THEN 'ELDORET BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '1320'   THEN 'ELDORET BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '121'   THEN 'EMBAKASI BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '212'   THEN 'EMBU BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '1030'   THEN 'GALLERIA MALL, NAIROBI'
WHEN cm.CUSTOMER_BRANCH =  '1030'   THEN 'GALLERIA MALL, NAIROBI'
WHEN cm.CUSTOMER_BRANCH =  '1050'   THEN 'GALLERIA MALL, NAIROBI'
WHEN cm.CUSTOMER_BRANCH =  '134'   THEN 'GARDEN CITY MALL BRANCH, NAIROBI'
WHEN cm.CUSTOMER_BRANCH =  '1380'   THEN 'GARDEN CITY MALL BRANCH, NAIROBI'
WHEN cm.CUSTOMER_BRANCH =  '216'   THEN 'GIKOMBA BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '231'   THEN 'GITHUNGURI BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '1400'   THEN 'GREENSPAN MALL BRANCH, NAIROBI'
WHEN cm.CUSTOMER_BRANCH =  '350'   THEN 'GRENADIER WESTLANDS BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '350'   THEN 'GRENADIER WESTLANDS BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '350'   THEN 'GRENADIER WESTLANDS BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '950'   THEN 'GRENADIER WESTLANDS BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '110'   THEN 'HARAMBEE BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '229'   THEN 'HOMABAY BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '300'   THEN 'INDUSTRIAL AREA BRANCH, NAIROBI'
WHEN cm.CUSTOMER_BRANCH =  '106'   THEN 'JUNCTION BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '1290'   THEN 'JUNCTION BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '224'   THEN 'KAHAWA SUKARI'
WHEN cm.CUSTOMER_BRANCH =  '224'   THEN 'KAHAWA SUKARI'
WHEN cm.CUSTOMER_BRANCH =  '210'   THEN 'KAKAMEGA BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '228'   THEN 'KAPSABET BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '207'   THEN 'KARATINA BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '119'   THEN 'KAREN BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '119'   THEN 'KAREN BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '1750'   THEN 'KAREN BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '234'   THEN 'KAWANGWARE BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '223'   THEN 'KENOL BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '125'   THEN 'KENYATTA AVENUE'
WHEN cm.CUSTOMER_BRANCH =  '211'   THEN 'KERICHO BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '233'   THEN 'KERUGOYA BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '233'   THEN 'KERUGOYA BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '215'   THEN 'KIAMBU BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '146'   THEN 'KILIFI BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '129'   THEN 'KILIMANI BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '131'   THEN 'KISII BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '1260'   THEN 'KISUMU TIVOLI BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '1260'   THEN 'KISUMU TIVOLI BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '1260'   THEN 'KISUMU TIVOLI BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '1260'   THEN 'KISUMU TIVOLI BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '149'   THEN 'KITALE BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '130'   THEN 'KITENGELA BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '232'   THEN 'KITUI BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '201'   THEN 'LAVINGTON BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '1500'   THEN 'LAVINGTON BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '230'   THEN 'LIMURU BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '230'   THEN 'LIMURU BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '128'   THEN 'LUNGA LUNGA SQUARE'
WHEN cm.CUSTOMER_BRANCH =  '1600'   THEN 'MACHAKOS BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '1600'   THEN 'MACHAKOS BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '145'   THEN 'MALINDI BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '850'   THEN 'MAMA NGINA STREET BRANCH, NAIROBI'
WHEN cm.CUSTOMER_BRANCH =  '250'   THEN 'MAMA NGINA STREET BRANCH, NAIROBI'
WHEN cm.CUSTOMER_BRANCH =  '400'   THEN 'MAMLAKA ROAD BRANCH, NAIROBI'
WHEN cm.CUSTOMER_BRANCH =  '114'   THEN 'MERU BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '114'   THEN 'MERU BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '226'   THEN 'MIGORI BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '103'   THEN 'MOI AVENUE BRANCH, MOMBASA'
WHEN cm.CUSTOMER_BRANCH =  '650'   THEN 'MOI AVENUE BRANCH, MOMBASA'
WHEN cm.CUSTOMER_BRANCH =  '218'   THEN 'MURANGA BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '218'   THEN 'MURANGA BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '209'   THEN 'MWEMBE TAYARI BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '209'   THEN 'MWEMBE TAYARI BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '217'   THEN 'NAIVASHA BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '1000'   THEN 'NAKURU NCBA CENTRE BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '1000'   THEN 'NAKURU NCBA CENTRE BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '1000'   THEN 'NAKURU NCBA CENTRE BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '1000'   THEN 'NAKURU NCBA CENTRE BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '107'   THEN 'NAKURU TOWER ONE BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '107'   THEN 'NAKURU TOWER ONE BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '107'   THEN 'NAKURU TOWER ONE BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '107'   THEN 'NAKURU TOWER ONE BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '144'   THEN 'NANYUKI BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '144'   THEN 'NANYUKI BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '203'   THEN 'NAROK BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '120'   THEN 'NCBA CENTRE BRANCH, NAIROBI'
WHEN cm.CUSTOMER_BRANCH =  '132'   THEN 'NCBA CENTRE BRANCH, NAIROBI'
WHEN cm.CUSTOMER_BRANCH =  '132'   THEN 'NCBA CENTRE BRANCH, NAIROBI'
WHEN cm.CUSTOMER_BRANCH =  '600'   THEN 'NCBA CENTRE BRANCH, NAIROBI'
WHEN cm.CUSTOMER_BRANCH =  '600'   THEN 'NCBA CENTRE BRANCH, NAIROBI'
WHEN cm.CUSTOMER_BRANCH =  '104'   THEN 'NCBA HOUSE'
WHEN cm.CUSTOMER_BRANCH =  '102'   THEN 'NCBA HOUSE'
WHEN cm.CUSTOMER_BRANCH =  '214'   THEN 'NGONG BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '109'   THEN 'NKURUMAH BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '235'   THEN 'NYAHURURU BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '235'   THEN 'NYAHURURU BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '750'   THEN 'NYALI CENTRE BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '750'   THEN 'NYALI CENTRE BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '750'   THEN 'NYALI CENTRE BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '206'   THEN 'NYERI BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '112'   THEN 'ONE KENTONS SQUARE BRANCH '
WHEN cm.CUSTOMER_BRANCH =  '112'   THEN 'ONE KENTONS SQUARE BRANCH '
WHEN cm.CUSTOMER_BRANCH =  '112'   THEN 'ONE KENTONS SQUARE BRANCH '
WHEN cm.CUSTOMER_BRANCH =  '112'   THEN 'ONE KENTONS SQUARE BRANCH '
WHEN cm.CUSTOMER_BRANCH =  '143'   THEN 'PARKLANDS BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '550'   THEN 'PARKSIDE TOWERS BRANCH, NAIROBI'
WHEN cm.CUSTOMER_BRANCH =  '111'   THEN 'PRESTIGE BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '1700'   THEN 'RIVER ROAD BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '126'   THEN 'RIVERSIDE BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '135'   THEN 'RONGAI BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '227'   THEN 'RUAKA BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '208'   THEN 'RUIRU EASTERN BYPASS BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '118'   THEN 'SAMEER PARK BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '204'   THEN 'SARIT CENTRE BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '1900'   THEN 'SWISSPORT BRANCH, NAIROBI'
WHEN cm.CUSTOMER_BRANCH =  '1800'   THEN 'SWISSPORT BRANCH, NAIROBI'
WHEN cm.CUSTOMER_BRANCH =  '205'   THEN 'SWISSPORT BRANCH, NAIROBI'
WHEN cm.CUSTOMER_BRANCH =  '205'   THEN 'SWISSPORT BRANCH, NAIROBI'
WHEN cm.CUSTOMER_BRANCH =  '500'   THEN 'SWISSPORT BRANCH, NAIROBI'
WHEN cm.CUSTOMER_BRANCH =  '105'   THEN 'THE MALL BRANCH, WESTLANDS'
WHEN cm.CUSTOMER_BRANCH =  '105'   THEN 'THE MALL BRANCH, WESTLANDS'
WHEN cm.CUSTOMER_BRANCH =  '105'   THEN 'THE MALL BRANCH, WESTLANDS'
WHEN cm.CUSTOMER_BRANCH =  '113'   THEN 'THIKA BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '1350'   THEN 'THIKA BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '1650'   THEN 'THIKA ROAD MALL BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '123'   THEN 'THIKA ROAD MALL BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '123'   THEN 'THIKA ROAD MALL BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '141'   THEN 'TWO RIVERS MALL BRANCH, NAIROBI'
WHEN cm.CUSTOMER_BRANCH =  '1430'   THEN 'TWO RIVERS MALL BRANCH, NAIROBI'
WHEN cm.CUSTOMER_BRANCH =  '148'   THEN 'UKUNDA BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '222'   THEN 'UTAWALA BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '800'   THEN 'VILLAGE MARKET BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '900'   THEN 'VILLAGE MARKET BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '450'   THEN 'VILLAGE MARKET BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '450'   THEN 'VILLAGE MARKET BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '200'   THEN 'WABERA STREET BRANCH, NAIROBI'
WHEN cm.CUSTOMER_BRANCH =  '147'   THEN 'WATAMU BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '225'   THEN 'WOTE BRANCH'
WHEN cm.CUSTOMER_BRANCH =  '1550'   THEN 'YAYA CENTRE BRANCH, NAIROBI'
WHEN cm.CUSTOMER_BRANCH =  '1470'   THEN 'YAYA CENTRE BRANCH, NAIROBI'
else cm.CUSTOMER_BRANCH_NAME
END AS MAIN_BRANCH,
case
	WHEN cm.CUSTOMER_BRANCH =  '122'   THEN 'NORTHERN'
WHEN cm.CUSTOMER_BRANCH =  '213'   THEN 'WESTERN'
WHEN cm.CUSTOMER_BRANCH =  '133'   THEN 'EASTERN '
WHEN cm.CUSTOMER_BRANCH =  '219'   THEN 'WESTERN'
WHEN cm.CUSTOMER_BRANCH =  '1060'   THEN 'COAST'
WHEN cm.CUSTOMER_BRANCH =  '1060'   THEN 'COAST'
WHEN cm.CUSTOMER_BRANCH =  '220'   THEN 'WESTERN'
WHEN cm.CUSTOMER_BRANCH =  '142'   THEN 'CENTRAL'
WHEN cm.CUSTOMER_BRANCH =  '101'   THEN 'NAIROBI '
WHEN cm.CUSTOMER_BRANCH =  '108'   THEN 'COAST'
WHEN cm.CUSTOMER_BRANCH =  '108'   THEN 'COAST'
WHEN cm.CUSTOMER_BRANCH =  '108'   THEN 'COAST'
WHEN cm.CUSTOMER_BRANCH =  '700'   THEN 'COAST'
WHEN cm.CUSTOMER_BRANCH =  '700'   THEN 'COAST'
WHEN cm.CUSTOMER_BRANCH =  '221'   THEN 'EASTERN '
WHEN cm.CUSTOMER_BRANCH =  '1320'   THEN 'WESTERN'
WHEN cm.CUSTOMER_BRANCH =  '1320'   THEN 'WESTERN'
WHEN cm.CUSTOMER_BRANCH =  '121'   THEN 'EASTERN '
WHEN cm.CUSTOMER_BRANCH =  '212'   THEN 'CENTRAL'
WHEN cm.CUSTOMER_BRANCH =  '1030'   THEN 'NORTHERN'
WHEN cm.CUSTOMER_BRANCH =  '1030'   THEN 'NORTHERN'
WHEN cm.CUSTOMER_BRANCH =  '1050'   THEN 'NORTHERN'
WHEN cm.CUSTOMER_BRANCH =  '134'   THEN 'NAIROBI '
WHEN cm.CUSTOMER_BRANCH =  '1380'   THEN 'NAIROBI '
WHEN cm.CUSTOMER_BRANCH =  '216'   THEN 'EASTERN '
WHEN cm.CUSTOMER_BRANCH =  '231'   THEN 'CENTRAL'
WHEN cm.CUSTOMER_BRANCH =  '1400'   THEN 'EASTERN '
WHEN cm.CUSTOMER_BRANCH =  '350'   THEN 'CENTRAL'
WHEN cm.CUSTOMER_BRANCH =  '350'   THEN 'CENTRAL'
WHEN cm.CUSTOMER_BRANCH =  '350'   THEN 'CENTRAL'
WHEN cm.CUSTOMER_BRANCH =  '950'   THEN 'CENTRAL'
WHEN cm.CUSTOMER_BRANCH =  '110'   THEN 'NAIROBI '
WHEN cm.CUSTOMER_BRANCH =  '229'   THEN 'WESTERN'
WHEN cm.CUSTOMER_BRANCH =  '300'   THEN 'EASTERN '
WHEN cm.CUSTOMER_BRANCH =  '106'   THEN 'NORTHERN'
WHEN cm.CUSTOMER_BRANCH =  '1290'   THEN 'NORTHERN'
WHEN cm.CUSTOMER_BRANCH =  '224'   THEN 'NAIROBI '
WHEN cm.CUSTOMER_BRANCH =  '224'   THEN 'NAIROBI '
WHEN cm.CUSTOMER_BRANCH =  '210'   THEN 'WESTERN'
WHEN cm.CUSTOMER_BRANCH =  '228'   THEN 'WESTERN'
WHEN cm.CUSTOMER_BRANCH =  '207'   THEN 'CENTRAL'
WHEN cm.CUSTOMER_BRANCH =  '119'   THEN 'NORTHERN'
WHEN cm.CUSTOMER_BRANCH =  '119'   THEN 'NORTHERN'
WHEN cm.CUSTOMER_BRANCH =  '1750'   THEN 'NORTHERN'
WHEN cm.CUSTOMER_BRANCH =  '234'   THEN 'NORTHERN'
WHEN cm.CUSTOMER_BRANCH =  '223'   THEN 'CENTRAL'
WHEN cm.CUSTOMER_BRANCH =  '125'   THEN 'NAIROBI '
WHEN cm.CUSTOMER_BRANCH =  '211'   THEN 'WESTERN'
WHEN cm.CUSTOMER_BRANCH =  '233'   THEN 'CENTRAL'
WHEN cm.CUSTOMER_BRANCH =  '233'   THEN 'CENTRAL'
WHEN cm.CUSTOMER_BRANCH =  '215'   THEN 'CENTRAL'
WHEN cm.CUSTOMER_BRANCH =  '146'   THEN 'COAST'
WHEN cm.CUSTOMER_BRANCH =  '129'   THEN 'NORTHERN'
WHEN cm.CUSTOMER_BRANCH =  '131'   THEN 'WESTERN'
WHEN cm.CUSTOMER_BRANCH =  '1260'   THEN 'WESTERN'
WHEN cm.CUSTOMER_BRANCH =  '1260'   THEN 'WESTERN'
WHEN cm.CUSTOMER_BRANCH =  '1260'   THEN 'WESTERN'
WHEN cm.CUSTOMER_BRANCH =  '1260'   THEN 'WESTERN'
WHEN cm.CUSTOMER_BRANCH =  '149'   THEN 'WESTERN'
WHEN cm.CUSTOMER_BRANCH =  '130'   THEN 'EASTERN '
WHEN cm.CUSTOMER_BRANCH =  '232'   THEN 'EASTERN '
WHEN cm.CUSTOMER_BRANCH =  '201'   THEN 'NORTHERN'
WHEN cm.CUSTOMER_BRANCH =  '1500'   THEN 'NORTHERN'
WHEN cm.CUSTOMER_BRANCH =  '230'   THEN 'NORTHERN'
WHEN cm.CUSTOMER_BRANCH =  '230'   THEN 'NORTHERN'
WHEN cm.CUSTOMER_BRANCH =  '128'   THEN 'EASTERN '
WHEN cm.CUSTOMER_BRANCH =  '1600'   THEN 'EASTERN '
WHEN cm.CUSTOMER_BRANCH =  '1600'   THEN 'EASTERN '
WHEN cm.CUSTOMER_BRANCH =  '145'   THEN 'COAST'
WHEN cm.CUSTOMER_BRANCH =  '850'   THEN 'CENTRAL'
WHEN cm.CUSTOMER_BRANCH =  '250'   THEN 'CENTRAL'
WHEN cm.CUSTOMER_BRANCH =  '400'   THEN 'NAIROBI '
WHEN cm.CUSTOMER_BRANCH =  '114'   THEN 'CENTRAL'
WHEN cm.CUSTOMER_BRANCH =  '114'   THEN 'CENTRAL'
WHEN cm.CUSTOMER_BRANCH =  '226'   THEN 'WESTERN'
WHEN cm.CUSTOMER_BRANCH =  '103'   THEN 'COAST'
WHEN cm.CUSTOMER_BRANCH =  '650'   THEN 'COAST'
WHEN cm.CUSTOMER_BRANCH =  '218'   THEN 'CENTRAL'
WHEN cm.CUSTOMER_BRANCH =  '218'   THEN 'CENTRAL'
WHEN cm.CUSTOMER_BRANCH =  '209'   THEN 'COAST'
WHEN cm.CUSTOMER_BRANCH =  '209'   THEN 'COAST'
WHEN cm.CUSTOMER_BRANCH =  '217'   THEN 'NORTHERN'
WHEN cm.CUSTOMER_BRANCH =  '1000'   THEN 'WESTERN'
WHEN cm.CUSTOMER_BRANCH =  '1000'   THEN 'WESTERN'
WHEN cm.CUSTOMER_BRANCH =  '1000'   THEN 'WESTERN'
WHEN cm.CUSTOMER_BRANCH =  '1000'   THEN 'WESTERN'
WHEN cm.CUSTOMER_BRANCH =  '107'   THEN 'WESTERN'
WHEN cm.CUSTOMER_BRANCH =  '107'   THEN 'WESTERN'
WHEN cm.CUSTOMER_BRANCH =  '107'   THEN 'WESTERN'
WHEN cm.CUSTOMER_BRANCH =  '107'   THEN 'WESTERN'
WHEN cm.CUSTOMER_BRANCH =  '144'   THEN 'CENTRAL'
WHEN cm.CUSTOMER_BRANCH =  '144'   THEN 'CENTRAL'
WHEN cm.CUSTOMER_BRANCH =  '203'   THEN 'NORTHERN'
WHEN cm.CUSTOMER_BRANCH =  '120'   THEN 'HEAD OFFICE'
WHEN cm.CUSTOMER_BRANCH =  '132'   THEN 'HEAD OFFICE'
WHEN cm.CUSTOMER_BRANCH =  '132'   THEN 'HEAD OFFICE'
WHEN cm.CUSTOMER_BRANCH =  '600'   THEN 'HEAD OFFICE'
WHEN cm.CUSTOMER_BRANCH =  '600'   THEN 'HEAD OFFICE'
WHEN cm.CUSTOMER_BRANCH =  '104'   THEN 'HEAD OFFICE'
WHEN cm.CUSTOMER_BRANCH =  '102'   THEN 'HEAD OFFICE'
WHEN cm.CUSTOMER_BRANCH =  '214'   THEN 'NORTHERN'
WHEN cm.CUSTOMER_BRANCH =  '109'   THEN 'COAST'
WHEN cm.CUSTOMER_BRANCH =  '235'   THEN 'NORTHERN'
WHEN cm.CUSTOMER_BRANCH =  '235'   THEN 'NORTHERN'
WHEN cm.CUSTOMER_BRANCH =  '750'   THEN 'COAST'
WHEN cm.CUSTOMER_BRANCH =  '750'   THEN 'COAST'
WHEN cm.CUSTOMER_BRANCH =  '750'   THEN 'COAST'
WHEN cm.CUSTOMER_BRANCH =  '206'   THEN 'CENTRAL'
WHEN cm.CUSTOMER_BRANCH =  '112'   THEN 'WESTERN'
WHEN cm.CUSTOMER_BRANCH =  '112'   THEN 'WESTERN'
WHEN cm.CUSTOMER_BRANCH =  '112'   THEN 'WESTERN'
WHEN cm.CUSTOMER_BRANCH =  '112'   THEN 'WESTERN'
WHEN cm.CUSTOMER_BRANCH =  '143'   THEN 'NAIROBI '
WHEN cm.CUSTOMER_BRANCH =  '550'   THEN 'EASTERN '
WHEN cm.CUSTOMER_BRANCH =  '111'   THEN 'NORTHERN'
WHEN cm.CUSTOMER_BRANCH =  '1700'   THEN 'NAIROBI '
WHEN cm.CUSTOMER_BRANCH =  '126'   THEN 'NORTHERN'
WHEN cm.CUSTOMER_BRANCH =  '135'   THEN 'NORTHERN'
WHEN cm.CUSTOMER_BRANCH =  '227'   THEN 'NAIROBI '
WHEN cm.CUSTOMER_BRANCH =  '208'   THEN 'CENTRAL'
WHEN cm.CUSTOMER_BRANCH =  '118'   THEN 'EASTERN '
WHEN cm.CUSTOMER_BRANCH =  '204'   THEN 'CENTRAL'
WHEN cm.CUSTOMER_BRANCH =  '1900'   THEN 'EASTERN '
WHEN cm.CUSTOMER_BRANCH =  '1800'   THEN 'EASTERN '
WHEN cm.CUSTOMER_BRANCH =  '205'   THEN 'EASTERN '
WHEN cm.CUSTOMER_BRANCH =  '205'   THEN 'EASTERN '
WHEN cm.CUSTOMER_BRANCH =  '500'   THEN 'EASTERN '
WHEN cm.CUSTOMER_BRANCH =  '105'   THEN 'CENTRAL'
WHEN cm.CUSTOMER_BRANCH =  '105'   THEN 'CENTRAL'
WHEN cm.CUSTOMER_BRANCH =  '105'   THEN 'CENTRAL'
WHEN cm.CUSTOMER_BRANCH =  '113'   THEN 'CENTRAL'
WHEN cm.CUSTOMER_BRANCH =  '1350'   THEN 'CENTRAL'
WHEN cm.CUSTOMER_BRANCH =  '1650'   THEN 'NAIROBI '
WHEN cm.CUSTOMER_BRANCH =  '123'   THEN 'NAIROBI '
WHEN cm.CUSTOMER_BRANCH =  '123'   THEN 'NAIROBI '
WHEN cm.CUSTOMER_BRANCH =  '141'   THEN 'NAIROBI '
WHEN cm.CUSTOMER_BRANCH =  '1430'   THEN 'NAIROBI '
WHEN cm.CUSTOMER_BRANCH =  '148'   THEN 'COAST'
WHEN cm.CUSTOMER_BRANCH =  '222'   THEN 'EASTERN '
WHEN cm.CUSTOMER_BRANCH =  '800'   THEN 'NAIROBI '
WHEN cm.CUSTOMER_BRANCH =  '900'   THEN 'NAIROBI '
WHEN cm.CUSTOMER_BRANCH =  '450'   THEN 'NAIROBI '
WHEN cm.CUSTOMER_BRANCH =  '450'   THEN 'NAIROBI '
WHEN cm.CUSTOMER_BRANCH =  '200'   THEN 'EASTERN '
WHEN cm.CUSTOMER_BRANCH =  '147'   THEN 'COAST'
WHEN cm.CUSTOMER_BRANCH =  '225'   THEN 'EASTERN '
WHEN cm.CUSTOMER_BRANCH =  '1550'   THEN 'NAIROBI '
WHEN cm.CUSTOMER_BRANCH =  '1470'   THEN 'NAIROBI '
end as REGION,
cm.CUST_MOB_PHONE, cm.CUST_EMAIL_ID,
ROW_NUMBER() OVER (PARTITION BY am.ACCOUNT_NUMBER ORDER BY am.EXTRACTION_DATE DESC) AS rn --latest entry
FROM dbcba.KE_Accounts_Master am
	INNER JOIN dbcba.KE_Customer_Master cm
		on am.CUSTOMER =cm.CUSTOMER_NUMBER   and cm.EXTRACTION_DATE= '2024-04-30'---(select max(processing_date) from dbcba.end_of_day)
		LEFT JOIN stgke.STG_ECB_TOTAL_EXPOSURE ex 
		on am.ACCOUNT_NUMBER=ex.RECID and ex.LOAD_DATE=am.EXTRACTION_DATE
	left join stgke.STG_AA_ARR_SETTLEMENT stl
		on stl.ID_COMP_1=am.ARRANGEMENT_ID
	left join STGKE.STG_AA_ARREARS pdo
		on am.ARRANGEMENT_ID=pdo.ARRANGEMENT_ID and pdo.EXTRACTION_DATE=am.EXTRACTION_DATE
where am.CATEGORY='3765'
AND am.VALUE_DATE BETWEEN '2024-03-01' AND  '2024-04-30' AND am.EXTRACTION_DATE=cm.EXTRACTION_DATE
and cm.CLASSIFICATION <>'B20' and cm.BUSINESS_SEGMENT not in ('260') 
and am.ARR_STATUS<>'AUTH'
) 
select *
--cast(SUM([DISBURSED_AMT_Kes_000]) as decimal(18,2)),
--cast(SUM([ONLINE_ACTUAL_BAL_Kes_000]) as decimal(12,2)),
--cast(sum([PAR PR_BALANCE_Kes_000])as decimal(12,2)),
--cast(sum([NPL PR_BALANCE_Kes_000])as decimal(12,2)),
--cast(sum([PAR PR_BALANCE_Kes_000])/SUM([DISBURSED_AMT_Kes_000]) as decimal(12,2)) AS PAR, 
--cast(sum([NPL PR_BALANCE_Kes_000])/SUM([DISBURSED_AMT_Kes_000]) as decimal(12,2)) AS NPL
FROM
LFALoansDasboard 
where  rn = 1 
--order by EXTRACTION_DATE DESC













