with LoansDasboard as
 (
select CAST(am.EXTRACTION_DATE AS DATE) as EXTRACTION_DATE ,cm.CUS_SHORT_NAME, am.CUSTOMER,am.ARRANGEMENT_ID,am.ACCOUNT_NUMBER,
case 
	when stl.PAYOUT_ACCOUNT is null or stl.PAYOUT_ACCOUNT='' then stl.PAYIN_ACCOUNT 
	else stl.PAYOUT_ACCOUNT 
end as SETTLEMENT_ACCOUNT,
cm.CLASSIFICATION,am.CATEGORY_DESC,am.CURRENCY,am.INTEREST_RATE,CONVERT(DECIMAL(18,0),am.TERM_AMOUNT) as DISBURSED_AMT, CONVERT(DECIMAL(18,0),ex.Deal_balance) as EXPOSURE_ACTUAL, 
case 
	when am.CURRENCY ='KES' then CONVERT(DECIMAL(18,0),ex.Deal_balance)
	else CONVERT(DECIMAL(18,0),ex.Deal_balance)*am.EXCHANGE_RATE
end as EXPOSURE_KES,
CONVERT(DECIMAL(18,0),(COALESCE (pdo.ARREARS_KES ,0)) ) AS ARREARS_KES, COALESCE (pdo.OD_DAYS ,0) as OD_DAYS,
DATE(am.VALUE_DATE) as VALUE_DATE, DATE(am.MATURITY_DATE ) as MATURITY_DATE,DATE(am.PAYMENT_START_DATE) as PAYMENT_START_DATE,
CONVERT(DECIMAL(18,2),am.REPAYMENT_AMT) as EMI,
DATEDIFF(MONTH,CONVERT(DATE,am.VALUE_DATE),CURRENT_TIMESTAMP) as MOB,
CASE 
    WHEN (DATEDIFF(MONTH,  CONVERT(DATE,am.PAYMENT_START_DATE),CURRENT_TIMESTAMP) = 1
          AND CONVERT(DECIMAL(18,2),(COALESCE (pdo.ARREARS_KES ,0)) ) >= (0.5*CONVERT(DECIMAL(18,2),am.REPAYMENT_AMT)) and COALESCE (pdo.OD_DAYS ,0)>0 
          and CONVERT(DATE,am.PAYMENT_START_DATE)<>CONVERT(DATE,am.MATURITY_DATE)) THEN 'FID'
    WHEN (DATEDIFF(MONTH,  CONVERT(DATE,am.VALUE_DATE),CURRENT_TIMESTAMP)= 3
          AND CONVERT(DECIMAL(18,2),(COALESCE (pdo.ARREARS_KES ,0)) ) >= (0.5*CONVERT(DECIMAL(18,2),am.REPAYMENT_AMT)) and COALESCE (pdo.OD_DAYS ,0)>0 ) THEN '3MOB'
       ELSE NULL
END AS EARLY_ALERT,
e.total_CREDITS as Last_Month_Turnover_SOW, am.ARR_STATUS AS LOAN_STATUS, 

case 
	when cm.BUSINESS_SEGMENT in ('270','250') then 'CONSUMER BANKING'
	when cm.BUSINESS_SEGMENT in ('200') then 'COMMERCIAL & BUSINESS BANKING'
end as BUSINESS_UNIT,
cm.SUB_SEGEMENT_DESC, cm.CUSTOMER_BRANCH_NAME ,cm.ACCOUNT_OFFICER_NAME 
FROM dbcba.KE_Accounts_Master am
	INNER JOIN dbcba.KE_Customer_Master cm
		on am.CUSTOMER =cm.CUSTOMER_NUMBER and am.EXTRACTION_DATE=cm.EXTRACTION_DATE
	left join  (select CUSTOMER_NUMBER ,sum(TOTAL_CREDITS) as total_CREDITS  from stgke.STG_SOW_TOTAL_CREDITS
				where TXN_YEAR_MONTH = (SELECT STRING(YEAR(DATEADD(MONTH, -1, MAX(processing_date))), '-', MONTH(DATEADD(MONTH, -1, MAX(processing_date)))) AS year_month
				FROM dbcba.end_of_day)
				group by CUSTOMER_NUMBER ) e
		on e.CUSTOMER_NUMBER=am.CUSTOMER 
	LEFT JOIN stgke.STG_ECB_TOTAL_EXPOSURE ex 
		on am.ACCOUNT_NUMBER=ex.RECID and ex.LOAD_DATE=am.EXTRACTION_DATE
	left join stgke.STG_AA_ARR_SETTLEMENT stl
		on stl.ID_COMP_1=am.ARRANGEMENT_ID
	left join STGKE.STG_AA_BILL_ARREARS  pdo
		on am.ARRANGEMENT_ID=pdo.ARRANGEMENT_ID and pdo.EXTRACTION_DATE=(select max(EXTRACTION_DATE) from STGKE.STG_AA_BILL_ARREARS )
where cm.EXTRACTION_DATE =(select max(processing_date) from dbcba.end_of_day)
and am.PRODUCT_LINE ='LENDING' AND am.ARR_STATUS in ('CURRENT','EXPIRED') and cm.BUSINESS_SEGMENT in ('270','250','200')
--and  am.CATEGORY not in ('3730','3731')
and cm.CLASSIFICATION <>'B20'

) 
select *-- CUSTOMER,CUS_SHORT_NAME,SUB_SEGEMENT_DESC,ACCOUNT_OFFICER_NAME, sum(EXPOSURE_KES) EXPOSURE_KES, sum(ARREARS_KES) ARREARS_KES, max(OD_DAYS) OD_DAYS 
from 
LoansDasboard