    WITH Day1Data AS ( 
	SELECT 
        a.ARRANGEMENT_ID,
        a.ACCOUNT_NUMBER,
           b.CUSTOMER_NUMBER,
        a.CUSTOMER_NAME,
          case 
	        when b.BUSINESS_SEGMENT in ('270','250') then 'CONSUMER BANKING'
			when b.BUSINESS_SEGMENT in ('200') then 'COMMERCIAL & BUSINESS BANKING'
		end as BUSINESS_SEGMENT_DESC,
        a.PRODUCT_LINE,
             a.PRODUCT_LINE_CLASSIFICATION,
                cast(a.EXPOSURE_KES as DECIMAL(18,2)) AS EXPOSURE_KES_DAY1,
                       CAST(a.ARREARS_KES AS DECIMAL(18,2)) AS ARREARS_DAY1,
            convert(date,a.EXTRACTION_DATE) AS EXTRACTION_DATE_day1,
        CONVERT(DATE,DATEADD(day, 8, a.EXTRACTION_DATE)) AS EXTRACTION_DATE_plus_8Days,
        CONVERT(DATE,DATEADD(day, 15, a.EXTRACTION_DATE)) AS EXTRACTION_DATE_plus_15Days, 
         a.OD_DAYS
          FROM 
        STGKE.STG_AA_BILL_ARREARS a
    INNER JOIN dbcba.KE_Customer_Master b ON b.CUSTOMER_NUMBER = a.CUSTOMER
        AND b.EXTRACTION_DATE = (SELECT MAX(processing_date) FROM dbcba.end_of_day)
          WHERE 
        LOWER(a.PRODUCT_LINE_CLASSIFICATION) NOT LIKE '%insurance%' AND UPPER(b.CLASSIFICATION) in ('A1','A2','A3','A4','A5','A6','A7','A8','A9')
        AND BUSINESS_SEGMENT IN ('270', '250', '200')  and lower(a.PRODUCT_LINE_CLASSIFICATION) not like '%export%'and lower(a.PRODUCT_LINE_CLASSIFICATION) not like '%lease%'
    and lower(a.PRODUCT_LINE_CLASSIFICATION) not like '%import%' and   a.ARREARS_KES IS NOT NULL
                AND a.EXTRACTION_DATE BETWEEN '2024-12-01' AND '2024-12-31' 			--<<Day1Data DATE>>  WITHING THE FULL MONTH
         and OD_DAYS IN (1)
 ),
Day8Data AS (
    SELECT 
        day8.ARRANGEMENT_ID,
        day8.ACCOUNT_NUMBER,
        CAST(COALESCE(day8.ARREARS_KES, 0) AS DECIMal(18,2)) AS ARREARS_DAY8,
       convert(date,day8.EXTRACTION_DATE) AS EXTRACTION_DATE_day8,
       day8.OD_DAYS
    FROM 
        STGKE.STG_AA_BILL_ARREARS day8
     inner join Day1Data day1 
     ON day8.ACCOUNT_NUMBER=day1.ACCOUNT_NUMBER
     where
     CONVERT(DATE,day8.EXTRACTION_DATE)=day1.EXTRACTION_DATE_plus_8Days
     AND CONVERT(DATE, day8.EXTRACTION_DATE) BETWEEN 
      DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()), 0)
  AND DATEADD(DAY, 7, DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()) + 1, 0))

    -- AND CONVERT(DATE,day8.EXTRACTION_DATE) BETWEEN '2024-12-01' AND '2025-01-08' --	--<<Day8Data DATE>> UP TO 8TH DAY NEXT MONTH 
     AND LOWER(day1.PRODUCT_LINE_CLASSIFICATION) NOT LIKE '%asset finance%'
     AND day8.EXTRACTION_DATE>day1.EXTRACTION_DATE_day1 
        ),
Day15Data AS (
    SELECT 
        day15.ARRANGEMENT_ID,
           day15.ACCOUNT_NUMBER,
        CAST(COALESCE(day15.ARREARS_KES, 0) AS DECIMAL(18,2)) AS ARREARS_DAY15,
       convert(date,day15.EXTRACTION_DATE) AS EXTRACTION_DATE_day15,
       day15.OD_DAYS
    FROM 
        STGKE.STG_AA_BILL_ARREARS day15
      inner join Day1Data day1 
     ON day15.ACCOUNT_NUMBER=day1.ACCOUNT_NUMBER
     where
     CONVERT(DATE,day15.EXTRACTION_DATE)=day1.EXTRACTION_DATE_plus_15Days
     AND CONVERT(DATE,day15.EXTRACTION_DATE) BETWEEN '2024-12-01' AND '2025-01-10' --	--<<Day15Data DATE>> UP TO AF DAY NEXT MONTH AFTER 25 EITHER (9 OR 10)
     AND LOWER(day1.PRODUCT_LINE_CLASSIFICATION) LIKE '%asset finance%'
     AND day15.EXTRACTION_DATE>day1.EXTRACTION_DATE_day1 
        ),
CombinedDATA AS (
select
		d1.ARRANGEMENT_ID,
        d1.ACCOUNT_NUMBER,
         d1.CUSTOMER_NUMBER,
        d1.CUSTOMER_NAME,
          d1.BUSINESS_SEGMENT_DESC,
        d1.PRODUCT_LINE,
               d1.PRODUCT_LINE_CLASSIFICATION,
              d1.EXPOSURE_KES_DAY1,
                  d1.ARREARS_DAY1,
       d1.EXTRACTION_DATE_day1,
            d8.ARREARS_DAY8,
        d8.EXTRACTION_DATE_day8,
        d15.ARREARS_DAY15,
        d15.EXTRACTION_DATE_day15,
                CASE 
            WHEN (LOWER(d1.PRODUCT_LINE_CLASSIFICATION) LIKE 'asset finance%' AND COALESCE(d1.ARREARS_DAY1, 0) > COALESCE(d15.ARREARS_DAY15, 0)) THEN COALESCE(d1.ARREARS_DAY1, 0) - COALESCE(d15.ARREARS_DAY15, 0)
            WHEN (LOWER(d1.PRODUCT_LINE_CLASSIFICATION) NOT LIKE 'asset finance%' AND COALESCE(d1.ARREARS_DAY1, 0) > COALESCE(d8.ARREARS_DAY8, 0)) THEN COALESCE(d1.ARREARS_DAY1, 0) - COALESCE(d8.ARREARS_DAY8, 0)
        ELSE 0
        END AS COLLECTED_AMOUNT
from Day1Data d1
left join Day8Data d8 on d8.ACCOUNT_NUMBER=d1.ACCOUNT_NUMBER 
left join Day15Data d15 on d15.ACCOUNT_NUMBER=d1.ACCOUNT_NUMBER 
 			WHERE 
    ARREARS_DAY1 IS NOT NULL
)
select *,
CASE 
        	when CONVERT (DECIMAL(15,2),COLLECTED_AMOUNT) >= CONVERT (DECIMAL(15,2),COALESCE (ARREARS_DAY1,0)) then 1
        	else  CONVERT (DECIMAL(15,2),CONVERT (DECIMAL(15,2),COLLECTED_AMOUNT)/CONVERT (DECIMAL(15,2),COALESCE (ARREARS_DAY1,0)))
        END [%AGE OF COLLECTED ARREARS AMOUNT],
    CASE 
        WHEN CONVERT (DECIMAL(15,2),COLLECTED_AMOUNT) >= CONVERT (DECIMAL(15,2),COALESCE (ARREARS_DAY1,0)) THEN 'CLEARED'
        WHEN COLLECTED_AMOUNT > (0.25*(COALESCE(ARREARS_DAY1,0))) THEN 'PARTIALLY CLEARED'
        ELSE 'NOT CLEARED'
    END AS "COLLECTION STATUS"
from CombinedDATA 

    
    
    
    
    
    