SELECT DISTINCT
op.CUSTOMER_OPEN_DATE,
    cm.CUSTOMER_NUMBER,
    CM.CUS_SHORT_NAME,
    cm.CUSTOMER_BRANCH_NAME,
    cm.ACCOUNT_OFFICER_NAME,
    cm.BUSINESS_SEGMENT_DESC,
    cm.SUB_SEGEMENT,
    cm.SUB_SEGEMENT_DESC,
    cm.TOWN_COUNTRY,
    cm.CUST_EMAIL_ID,
    cm.CUST_MOB_PHONE,
    CM.INDUSTRY_DESCRIPTION AS CUSTOMER_INDUSTRY
FROM dbcba.KE_Accounts_List al
LEFT JOIN dbcba.KE_Customer_Master cm
    ON al.CUSTOMER = cm.CUSTOMER_NUMBER
   AND cm.EXTRACTION_DATE = (SELECT MAX(processing_date) FROM dbcba.end_of_day)
LEFT JOIN (SELECT DISTINCT MIN(EXTRACTION_DATE) as CUSTOMER_OPEN_DATE, CUSTOMER_NUMBER 
		FROM
		DBCBA.KE_Customer_Master 
		GROUP BY CUSTOMER_NUMBER ) op
		on op.CUSTOMER_NUMBER=al.CUSTOMER
WHERE al.PRODUCT_LINE = 'ACCOUNTS'
  AND CAST(al.OPENING_DATE AS DATE) BETWEEN DATEADD(DAY, -30, CURRENT DATE) AND CURRENT DATE
  AND CAST(op.CUSTOMER_OPEN_DATE AS DATE) BETWEEN DATEADD(DAY, -30, CURRENT DATE) AND CURRENT DATE
  AND cm.BUSINESS_SEGMENT = '200' AND CM.SUB_SEGEMENT NOT IN('730')
  and al.ONLINE_ACTUAL_BAL >=0 AND CM.CLASSIFICATION IN ('A1','A2','A3','A4','A5')
  AND CM.AML_RISK_CLASS = 'LOW' AND CM.TOWN_COUNTRY IN ('NAIROBI','KIAMBU','MACHAKOS','KAJIADO')









