SELECT 
   	saai.RECID,
   	sl.RECID AS LIMIT_ID,
   	sa.ACCOUNT_TITLE_1,
    ACCOUNT,
    sa.CUSTOMER ,
    sa.ARRANGEMENT_ID,
 	sl.LIMIT_CURRENCY,  
    LIMIT_PRODUCT,
   	INTERNAL_AMOUNT,
   	al.ONLINE_ACTUAL_BAL as CURRENT_ACTUAL_BALANCE,
    CAST(sl.ONLINE_LIMIT_DATE AS DATE),
    CAST(EXPIRY_DATE AS DATE),
CASE
	WHEN sl.LIMIT_CURRENCY = 'KES' then al.ONLINE_ACTUAL_BAL
	else CAST(al.ONLINE_ACTUAL_BAL AS DECIMAL(18,2))*CAST(ex.[EXCHANGE RATE] AS DECIMAL(18,2))
END as ONLINE_ACTUAL_BAL_KES,
CASE 
   	WHEN CAST(EXPIRY_DATE AS DATE) <= CURRENT TIMESTAMP THEN 'EXPIRED'
   	ELSE 'ACTIVE'
END AS STATUS,
CASE 
  	WHEN CAST(EXPIRY_DATE AS DATE) > CURRENT TIMESTAMP THEN 
   	CAST(DATEDIFF(MONTH, CURRENT TIMESTAMP, CAST(EXPIRY_DATE AS DATE)) AS VARCHAR)
   	ELSE 'EXPIRED'
END AS MONTHS_TO_EXPIRY,  -- Ensures VARCHAR type for both branches
CASE 
	when cm.BUSINESS_SEGMENT in ('270','250') then 'CONSUMER BANKING'
	when cm.BUSINESS_SEGMENT in ('200') then 'COMMERCIAL & BUSINESS BANKING'
END as BUSINESS_UNIT,
	cm.SUB_SEGEMENT_DESC,
 	cm.CUSTOMER_BRANCH_NAME,
 	cm.ACCOUNT_OFFICER_NAME ,
    saai.ACTIVITY,
    saai.FIXED_RATE,
    saai.FLOATING_INDEX,
    saai.MARGIN_OPER,
    saai.MARGIN_RATE,
    saai.EFFECTIVE_RATE,
    saai.EFFECTIVE_RATE_1,
    saai.TIER_AMOUNT,
    LAST_DRAW_DATE,
    saai.DAY_BASIS,
    saai.RATE_TIER_TYPE,
    saai.ID_COMP_1,
    INTERNAL_AMOUNT,
    APPROVAL_DATE,
    REVIEW_FREQUENCY,
    ONLINE_LIMIT,
    AVAIL_AMT AS AVAILABLE_AMT,
    sl.CURR_NO,
    sl.CO_CODE,
    sl.AUTHORISER,
    COUNTRY_OF_RISK,
    sl.INPUTTER,
    OD_INT_KEY,
    sl.DATE_TIME
   FROM 
    STGKE.STG_LIMIT sl 
LEFT JOIN 
    STGKE.STG_ACCOUNT sa ON sa.RECID = sl.ACCOUNT
LEFT JOIN 
    STGKE.STG_AA_ARR_INTEREST saai ON saai.ID_COMP_1 = sa.ARRANGEMENT_ID
LEFT JOIN 
	dbcba.KE_Accounts_List al on al.ACCOUNT_NUMBER = sl.ACCOUNT 
LEFT JOIN 
		(select RECID AS CURRENCY,
		CASE 
		WHEN RECID='KES' THEN '1'
		ELSE MID_REVAL_RATE
		END AS [EXCHANGE RATE]
		from STGKE.STG_CURRENCY ) AS ex on ex.CURRENCY=sl.LIMIT_CURRENCY 
LEFT JOIN
    dbcba.KE_Customer_Master cm ON sa.CUSTOMER = cm.CUSTOMER_NUMBER and cm.EXTRACTION_DATE =(select max(processing_date) from dbcba.end_of_day)
WHERE
    LIMIT_PRODUCT = '100'
    AND EXPIRY_DATE IS NOT NULL 
    AND EXPIRY_DATE <> ''
    and cm.BUSINESS_SEGMENT IN ('270','250','200')
    and sl.BRANCH_APPROVED not in ('YES')
    --and  sa.CUSTOMER ='119424'
     ---and LIMIT_CURRENCY not like '%KES%'
    ---AND SL.ACCOUNT ='1016880111'
   -- and  	saai.RECID is null
    
  select *
  from    STGKE.STG_LIMIT sl 
  where RECID in  ('785735.0000100.09')
--and sl.BRANCH_APPROVED not in ('YES')
  
  
  select *
  FROM STGKE.STG_AA_ARR_INTEREST
   
    

    


    

