select  distinct TRANS_REFERENCE,a.ACCOUNT_NUMBER, d.ARRANGEMENT_ID ,abs(AMOUNT_LCY),a.CURRENCY,ACCOUNT_TITLE_1,
b.EXPIRY_DATE, b.ONLINE_LIMIT_DATE, b.ONLINE_LIMIT_DATE, b.LIMIT_PRODUCT,
INTERNAL_AMOUNT,APPROVAL_DATE,REVIEW_FREQUENCY,ONLINE_LIMIT,AVAIL_AMT as AVAILABLE_AMT
from  dbcba.KE_ACCOUNT_TRANSACTIONS a
left  join STGKE.STG_LIMIT b on b.ACCOUNT =a.ACCOUNT_NUMBER
left join STGKE.STG_ACCOUNT_DEBIT_INT c on c.ACCOUNT_NUMBER=a.ACCOUNT_NUMBER
left join STGKE.STG_ACCOUNT d  on d.recid=a.ACCOUNT_NUMBER
where --a.ACCOUNT_NUMBER ='6928600048'and
BOOKING_DATE BETWEEN '2024-12-01' and '2024-12-31'
and NARRATIVE='Debit Interest'
and b.LIMIT_PRODUCT='100'


