SELECT a.BILL_REFERENCE, 
       a.ARRANGEMENT_ID, 
       c.CUS_SHORT_NAME,
       b.CUSTOMER,
       b.account_number as ACCOUNT_NUMBER,
       case when stl.PAYOUT_ACCOUNT is null or stl.PAYOUT_ACCOUNT='' then stl.PAYIN_ACCOUNT else stl.PAYOUT_ACCOUNT end as SETTLEMENT_ACCOUNT,
      CAST(a.PAYMENT_DATE AS DATE) 'PAYMENT_DATE', 
      CAST(a.SET_ST_CHG_DT AS DATE)'SETTLED_DATE',
      A.SETTLE_STATUS ,
      A.BILL_TYPE,
       a.CURRENCY,
       EFFECTIVE_RATE,
       MONTH(CAST( a.PAYMENT_DATE AS DATE))AS MONTH,
          YEAR(CAST( a.PAYMENT_DATE AS DATE))AS PAYMENT_YEAR,
      CONVERT(DECIMAL(18, 2),  a.OR_TOTAL_AMOUNT) as 'TOTAL_BILLED', 
       CONVERT(DECIMAL(18, 2), a.OR_PR_AMT) AS 'Principal amount ACTUAL ',
         case when  b.CURRENCY = 'KES' then  CONVERT(DECIMAL(18, 2), a.OR_PR_AMT)
    else   CONVERT(DECIMAL(18, 2), a.OR_PR_AMT) *b.EXCHANGE_RATE end    AS 'Principal amount KES ' ,
          CONVERT(DECIMAL(18, 2),  a.PRINCIPALINT) AS 'Principal Interest ACTUAL',
          case when  b.CURRENCY = 'KES' then     CONVERT(DECIMAL(18, 2),  a.PRINCIPALINT)
    else      CONVERT(DECIMAL(18, 2),  a.PRINCIPALINT)*b.EXCHANGE_RATE end    AS 'Principal Interest KES ' ,
         CONVERT(DECIMAL(18, 2),   a.PENALTYINT) AS 'Penalty interest ACTUAL',
            case when  b.CURRENCY = 'KES' then      CONVERT(DECIMAL(18, 2),   a.PENALTYINT) 
    else    CONVERT(DECIMAL(18, 2),   a.PENALTYINT) *b.EXCHANGE_RATE end    AS 'Penalty interest KES ' ,
        convert(DECIMAL(18,2),a.REPAY_AMOUNT_2) as REPAY_AMOUNT_2_ACTUAL,
    --CASE 
    	--WHEN b.CURRENCY = 'KES' then  convert(DECIMAL(18,2),a.REPAY_AMOUNT_2)
    	--else  convert(DECIMAL(18,2),a.REPAY_AMOUNT_2)*b.EXCHANGE_RATE
    --END as REPAY_AMOUNT_2_KES,
     case when  b.CURRENCY = 'KES' then CTE.DEAL_BALANCE
else  CTE.DEAL_BALANCE*b.EXCHANGE_RATE end   as EXPOSURE_KES ,
CTE.DEAL_BALANCE  as  EXPOSURE_ACTUAL ,
case when b.CURRENCY = 'KES' then b.TERM_AMOUNT
else b.TERM_AMOUNT*b.EXCHANGE_RATE end as DISBURSED_KES
,OPENING_DATE AS 'ACCOUNT_OPEN_DATE'
       ,MATURITY_DATE AS 'LOAN_MATURITY_DATE'
       ,cast(b.REPAYMENT_AMT as double) as EMI_ACTUAL
       ,C.CUSTOMER_BRANCH,C.CUSTOMER_BRANCH_NAME
       --,b.ACCOUNT_BRANCH,ACCOUNT_BRANCH_NAME 
       ,c.CUS_ACC_OFFICER as ACCOUNT_OFFICER_CODE,c.ACCOUNT_OFFICER_NAME
       ,c.SUB_SEGEMENT,c.SUB_SEGEMENT_DESC,c.BUSINESS_SEGMENT,c.BUSINESS_SEGMENT_DESC ,
e.total_CREDITS as SOW_CREDITS
FROM STGKE.STG_AA_BILL_DETAILS a
INNER join  dbcba.ke_accounts_master b on a.ARRANGEMENT_ID = b.ARRANGEMENT_ID and b.EXTRACTION_DATE =(select max(processing_date) from dbcba.end_of_day)
inner join  dbcba.ke_customer_master c on b.CUSTOMER=c.customer_number and C.EXTRACTION_DATE =(select max(processing_date) from dbcba.end_of_day)
left join stgke.STG_AA_ARR_SETTLEMENT stl on a.ARRANGEMENT_ID=stl.id_comp_1
left join  (select CUSTOMER_NUMBER ,sum(TOTAL_CREDITS) as total_CREDITS  from stgke.STG_SOW_TOTAL_CREDITS
where TXN_YEAR_MONTH ='2024-7'
group by CUSTOMER_NUMBER ) e
on e.CUSTOMER_NUMBER=b.CUSTOMER  
LEFT   join  stgke.STG_ECB_TOTAL_EXPOSURE CTE  on CTE.RECID  =b.ACCOUNT_NUMBER  and EXPOSURE_KES >0  
left join STGKE.STG_AA_ARR_INTEREST d on d.ID_COMP_1=a.ARRANGEMENT_ID
WHERE --a.ARRANGEMENT_ID in ('AA24176PX3YT','AA24066GD5KQ')
   --a.BILL_REFERENCE = 'AABILL2421230RJR' 
  PAYMENT_YEAR =2024 
 --AND a.PRINCIPALINT IS NULL AND SETTLE_STATUS ='REPAID' AND EXPOSURE_KES IS NOT NULL
AND MONTH=7
AND C.BUSINESS_SEGMENT NOT IN ('150')
AND B.PRODUCT_LINE ='LENDING'
and BILL_TYPE ='PAYMENT'
and CUSTOMER='523777'
ORDER BY a.ARRANGEMENT_ID DESC