WITH Day1Data AS ( 
    SELECT 
        a.ARRANGEMENT_ID,
        a.ACCOUNT_NUMBER,
        a.CUSTOMER_NAME,
        a.PRODUCT_LINE,
        b.CUSTOMER_NUMBER,
        a.PRODUCT_LINE_CLASSIFICATION,
        a.BUSINESS_SEGMENT_DESC,
        a.EXTRACTION_DATE AS EXTRACTION_DATE_day1,
        a.EXPOSURE_KES AS EXPOSURE_KES_DAY1,
        a.ARREARS_KES AS ARREARS_DAY1,
        a.OD_DAYS
    FROM 
        STGKE.STG_AA_BILL_ARREARS a
    INNER JOIN dbcba.KE_Customer_Master b ON b.CUSTOMER_NUMBER = a.CUSTOMER
        AND b.EXTRACTION_DATE = (SELECT MAX(processing_date) FROM dbcba.end_of_day)
        AND BUSINESS_SEGMENT IN ('270', '250', '200')
    WHERE 
        LOWER(a.PRODUCT_LINE_CLASSIFICATION) NOT LIKE '%insurance%'
                AND a.EXTRACTION_DATE BETWEEN '2024-11-01' AND '2024-11-30' 			--<<Day1Data DATE>>  WITHING THE FULL MONTH
         and OD_DAYS = (
        				SELECT MIN(OD_DAYS)
        				FROM STGKE.STG_AA_BILL_ARREARS
        				WHERE OD_DAYS IN (1, 2, 3)
        				AND EXTRACTION_DATE BETWEEN '2024-11-01' AND '2024-11-30'  ) --<<Day1Data DATE>>  WITHING THE FULL MONTH
      ),
Day8Data AS (
    SELECT 
        ARRANGEMENT_ID,
        ACCOUNT_NUMBER,
        COALESCE(ARREARS_KES, 0) AS ARREARS_DAY8,
        EXTRACTION_DATE AS EXTRACTION_DATE_day8
    FROM 
        STGKE.STG_AA_BILL_ARREARS
    WHERE 
        EXTRACTION_DATE BETWEEN '2024-11-01' AND '2024-12-08'   	--	--<<Day8Data DATE>> UP TO 8TH DAY NEXT MONTH 
        and OD_DAYS = (
        				SELECT MIN(OD_DAYS)
        				FROM STGKE.STG_AA_BILL_ARREARS
        				WHERE OD_DAYS IN (8, 9, 10)
        				AND EXTRACTION_DATE BETWEEN '2024-11-01' AND '2024-12-08')  --	--<<Day8Data DATE>><<Day8Data DATE>> UP TO 8TH DAY NEXT MONTH
        ),
Day15Data AS (
    SELECT 
        ACCOUNT_NUMBER,
        COALESCE (ARREARS_KES,0) AS ARREARS_DAY15,
        EXTRACTION_DATE AS EXTRACTION_DATE_day15,OD_DAYS
    FROM 
        STGKE.STG_AA_BILL_ARREARS
    WHERE 
        EXTRACTION_DATE BETWEEN '2024-11-01' AND '2024-12-11' 				--	--<<Day15Data DATE>> UP TO AF DAY NEXT MONTH AFTER 25 EITHER (9 OR 10)
        and OD_DAYS = (
        		SELECT MIN(OD_DAYS)
        		FROM STGKE.STG_AA_BILL_ARREARS
        		WHERE OD_DAYS IN (15,16,17)
        		AND EXTRACTION_DATE BETWEEN '2024-11-01' AND '2024-12-11')     --	--<<Day15Data DATE>> UP TO AF DAY NEXT MONTH AFTER 25 EITHER (9 OR 10)
  ),
CombinedDATA AS (
    SELECT 
        d1.ARRANGEMENT_ID,
        d1.ACCOUNT_NUMBER,
        d1.CUSTOMER_NAME,
        d1.CUSTOMER_NUMBER,
        d1.BUSINESS_SEGMENT_DESC,
        d1.PRODUCT_LINE,
        d1.PRODUCT_LINE_CLASSIFICATION,
        CONVERT(DECIMAL(15,2),d1.EXPOSURE_KES_DAY1) AS EXPOSURE_KES_DAY1,
        CONVERT(DECIMAL(15,2),d1.ARREARS_DAY1) AS ARREARS_DAY1,
        CONVERT(DATE,d1.EXTRACTION_DATE_day1) AS EXTRACTION_DATE_day1,
        CONVERT(DECIMAL(15,2),d8.ARREARS_DAY8) AS ARREARS_DAY8,
         CONVERT(DATE,d8.EXTRACTION_DATE_day8) AS EXTRACTION_DATE_day8,
       CONVERT(DECIMAL(15,2),d15.ARREARS_DAY15) AS ARREARS_DAY15,
    CONVERT(DATE,d15.EXTRACTION_DATE_day15) AS EXTRACTION_DATE_day15,
             CASE 
            WHEN (LOWER(d1.PRODUCT_LINE_CLASSIFICATION) LIKE 'asset finance%' AND COALESCE(d1.ARREARS_DAY1, 0) > COALESCE(d15.ARREARS_DAY15, 0)) THEN COALESCE(d1.ARREARS_DAY1, 0) - COALESCE(d15.ARREARS_DAY15, 0)
            WHEN (LOWER(d1.PRODUCT_LINE_CLASSIFICATION) NOT LIKE 'asset finance%' AND COALESCE(d1.ARREARS_DAY1, 0) > COALESCE(d8.ARREARS_DAY8, 0)) THEN COALESCE(d1.ARREARS_DAY1, 0) - COALESCE(d8.ARREARS_DAY8, 0)
            ELSE 0
        END AS COLLECTED_AMOUNT
    FROM 
        Day1Data d1
    LEFT JOIN Day8Data d8 ON d1.ACCOUNT_NUMBER = d8.ACCOUNT_NUMBER 
        AND d8.EXTRACTION_DATE_day8 >= d1.EXTRACTION_DATE_day1
        AND (DATEDIFF(DAY, d1.EXTRACTION_DATE_day1, d8.EXTRACTION_DATE_day8) <= 10 OR d8.EXTRACTION_DATE_day8 IS NULL)
           AND LOWER(d1.PRODUCT_LINE_CLASSIFICATION) NOT LIKE '%asset finance%'
    LEFT JOIN Day15Data d15 ON d1.ACCOUNT_NUMBER = d15.ACCOUNT_NUMBER 
        AND d15.EXTRACTION_DATE_day15 >= d1.EXTRACTION_DATE_day1
        AND (DATEDIFF(DAY, d1.EXTRACTION_DATE_day1, d15.EXTRACTION_DATE_day15) <= 17 OR d15.EXTRACTION_DATE_day15 IS NULL)
        AND LOWER(d1.PRODUCT_LINE_CLASSIFICATION) LIKE '%asset finance%'	
)
SELECT 
		ARRANGEMENT_ID,
        ACCOUNT_NUMBER,
        cd.CUSTOMER_NUMBER,
        CUSTOMER_NAME,
        case 
	        when cm.BUSINESS_SEGMENT in ('270','250') then 'CONSUMER BANKING'
			when cm.BUSINESS_SEGMENT in ('200') then 'COMMERCIAL & BUSINESS BANKING'
		end as BUSINESS_SEGMENT_DESC,
                    PRODUCT_LINE,
        PRODUCT_LINE_CLASSIFICATION,
        EXPOSURE_KES_DAY1,
         ARREARS_DAY1,
       EXTRACTION_DATE_day1,
     ARREARS_DAY8,
         EXTRACTION_DATE_day8,
       ARREARS_DAY15,
    EXTRACTION_DATE_day15,
        CASE 
        	when CONVERT (DECIMAL(15,2),COLLECTED_AMOUNT) >= CONVERT (DECIMAL(15,2),COALESCE (ARREARS_DAY1,0)) then 1
        	else  CONVERT (DECIMAL(15,2),CONVERT (DECIMAL(15,2),COLLECTED_AMOUNT)/CONVERT (DECIMAL(15,2),COALESCE (ARREARS_DAY1,0)))
        END [%AGE OF COLLECTED ARREARS AMOUNT],
CONVERT (DECIMAL(15,2),COLLECTED_AMOUNT) AS [COLLECTED AMOUNT],
    CASE 
        WHEN CONVERT (DECIMAL(15,2),COLLECTED_AMOUNT) >= CONVERT (DECIMAL(15,2),COALESCE (ARREARS_DAY1,0)) THEN 'CLEARED'
        WHEN COLLECTED_AMOUNT > (0.25*(COALESCE(ARREARS_DAY1,0))) THEN 'PARTIALLY CLEARED'
        ELSE 'NOT CLEARED'
    END AS "COLLECTION STATUS"
FROM 
    CombinedDATA cd
    INNER JOIN    
    		(select CUSTOMER_NUMBER,BUSINESS_SEGMENT,BUSINESS_SEGMENT_DESC, SUB_SEGEMENT, SUB_SEGEMENT_DESC, CLASSIFICATION,
    		CUSTOMER_BRANCH_NAME ,ACCOUNT_OFFICER_NAME ,CUS_ACC_OFFICER
   			from
   			dbcba.KE_Customer_Master
   			where EXTRACTION_DATE=(select max(processing_date) from dbcba.end_of_day)) cm
			on cd.CUSTOMER_NUMBER =cm.CUSTOMER_NUMBER 
			WHERE 
    ARREARS_DAY1 IS NOT NULL
    and cm.BUSINESS_SEGMENT in ('270','250','200') AND UPPER(cm.CLASSIFICATION) in ('A1','A2','A3','A4','A5','A6','A7','A8','A9')
    and lower(cd.PRODUCT_LINE_CLASSIFICATION) not like '%export%'and lower(cd.PRODUCT_LINE_CLASSIFICATION) not like '%lease%'
    and lower(cd.PRODUCT_LINE_CLASSIFICATION) not like '%import%'
    --AND EXPOSURE_KES_DAY1 IS NULL
    --AND ARRANGEMENT_ID IN ('AA22269CY5ZC')
ORDER BY 
    ACCOUNT_NUMBER;
   

   
   
