SELECT 
    CUSTOMER_NUMBER, 
    CUS_SHORT_NAME, 
    SUB_SEGEMENT_DESC,
    BUSINESS_SEGMENT_DESC,
    CASE 
                WHEN TRIM(CUST_MOB_PHONE) IS NOT NULL AND TRIM(CUST_MOB_PHONE) <> '' THEN CUST_MOB_PHONE
        WHEN TRIM(PHONE_1) IS NOT NULL AND TRIM(PHONE_1) <> '' THEN PHONE_1
        WHEN TRIM(CUST_OFF_PHONE) IS NOT NULL AND TRIM(CUST_OFF_PHONE) <> '' THEN CUST_OFF_PHONE
        WHEN TRIM(OFF_PHONE) IS NOT NULL AND TRIM(OFF_PHONE) <> '' THEN OFF_PHONE
        ELSE NULL
    END AS CUST_PHONE,
    CUST_EMAIL_ID AS CUST_EMAIL,
    DATE_OF_BIRTH,
    *
FROM
    DBCBA.KE_Customer_Master 
WHERE 
    EXTRACTION_DATE = (
        SELECT MAX(processing_date) 
        FROM DBCBA.end_of_day)
        --and CUSTOMER_NUMBER in ()
--and CUSTOMER_NUMBER  in ('256992')
and lower(CUS_SHORT_NAME) like '%kaiba%' --and lower(CUS_SHORT_NAME) like '%njuguna%'
AND SUB_SEGEMENT_DESC LIKE '%HUMAN%'




