---TRAINING_TEST_DATA PLUS CRB DATA PLUS PPC
---TRAINING_TEST_DATA AND CRB DATA
WITH od_dpd_max AS (
    SELECT
        OD.[CUSTOMER NO] AS CUSTOMER,
        COALESCE(MAX(ISNULL(OD.[EXCESS DAYS], 0)), 0) AS max_od_days
    FROM
        --STGKE.STG_AA_DAYS_EXCESS_BKP OD
        STGKE.STG_AA_DAYS_EXCESS OD
    INNER JOIN DBCBA.KE_ACCOUNTS_MASTER ACC ON
        OD.[ACCOUNT NUMBER] = ACC.ACCOUNT_NUMBER
    LEFT JOIN DBCBA.KE_CUSTOMER_MASTER CM ON 
        CM.CUSTOMER_NUMBER = OD.[CUSTOMER NO]
    WHERE 
        OD.EXTRACTION_DATE BETWEEN DATEADD(DAY, -732, GETDATE()-1) AND GETDATE()-1
        AND ACC.EXTRACTION_DATE = (SELECT MAX(EXTRACTION_DATE) FROM DBCBA.KE_ACCOUNTS_MASTER)
        AND CM.EXTRACTION_DATE = (SELECT MAX(EXTRACTION_DATE) FROM DBCBA.KE_CUSTOMER_MASTER)
        AND OD.[CUSTOMER NO] <> ''
        --AND CM.CLASSIFICATION IN ('A1', 'A2', 'A3', 'A4', 'A5', 'A6') 
        AND CM.BUSINESS_SEGMENT IN ('270', '250')
        AND ACC.PRODUCT_LINE = 'ACCOUNTS' 
        --AND OD.[CUSTOMER NO] IN ('703811')
    GROUP BY 
        OD.[CUSTOMER NO]
),
loan_dpd_max AS (
    SELECT
        BIL.CUSTOMER AS CUSTOMER,
        COALESCE(MAX(ISNULL(BIL.OD_DAYS, 0)), 0) AS max_loan_dpd

    FROM
        STGKE.STG_AA_BILL_ARREARS BIL
    LEFT JOIN DBCBA.KE_CUSTOMER_MASTER CM ON 
        CM.CUSTOMER_NUMBER = BIL.CUSTOMER
    WHERE 
        BIL.EXTRACTION_DATE BETWEEN DATEADD(DAY, -732, GETDATE()-1) AND GETDATE()-1
        AND CM.EXTRACTION_DATE = (select PROCESSING_DATE   from dbcba.end_of_day WHERE LATEST_RECORD = 'Y')--(SELECT MAX(EXTRACTION_DATE) FROM DBCBA.KE_CUSTOMER_MASTER)
        AND BIL.CUSTOMER <> ''
        --AND CM.CLASSIFICATION IN ('A1', 'A2', 'A3', 'A4', 'A5', 'A6') 
        AND CM.BUSINESS_SEGMENT IN ('270', '250')
        AND (BIL.OD_DAYS IS NOT NULL)
        --AND BIL.CUSTOMER IN ('703811')
    GROUP BY 
        BIL.CUSTOMER
)
,
all_dpds AS 
(
SELECT 
    COALESCE(od_dpd_max.CUSTOMER, loan_dpd_max.CUSTOMER) AS CUSTOMER,
    --od_dpd_max.max_od_days,
    --loan_dpd_max.max_loan_dpd,
    -- Use COALESCE within the CASE statement to ensure no NULL values in MAX_DAYS
    CASE 
        WHEN COALESCE(od_dpd_max.max_od_days, 0) >= COALESCE(loan_dpd_max.max_loan_dpd, 0) THEN COALESCE(od_dpd_max.max_od_days, 0)
        ELSE COALESCE(loan_dpd_max.max_loan_dpd, 0)
    END AS max_dpd_train_test
FROM 
    od_dpd_max
FULL OUTER JOIN loan_dpd_max
    ON loan_dpd_max.CUSTOMER = od_dpd_max.CUSTOMER

--WHERE COALESCE(od_dpd_max.CUSTOMER, loan_dpd_max.CUSTOMER) IN ('891823', '599862', '618507', '868406')
),

crb_data AS 
(
SELECT 
    CAST(CAST(CLIENTID AS INT) AS VARCHAR) AS CLIENTID,
	NATIONALID,
	PASSPORTNO,
	NUMBEROF_ACCOUNTS,
	OPENACCOUNT,
	PERFORMING,
	NONPERFORMING,
	CLOSED,
	CURRENTINARREARS,
	ARREARS0DAYS,
	MAXARREARS,
	MAXARREARSLAST12MONTHS,
	MAXARREARSLAST3MONTHS,
	PRINCIPALAMOUNT,
	SCHEDULEDPAYMENTAMT,
	CREDITAPPLICATIONSDONE,
	CURRENTBALANCEAMOUNT,
	SUBSCRIBERCURRENTBALANCEAMOUNT,
	PASTDUEAMOUNT,
	NUMBEROFENQUIRIES,
	ENQUIRIES30DAYS,
	ENQUIRIES90DAYS,
	SCORE AS CRB_TU_SCORE,
	MOBILE_TOTAL,
	MOBILE_PERFORMING,
	MOBILE_NONPERFORMING,
	MOBILE_PRINCIPALAMOUNT
	

FROM dbcba.LEND_FOR_ALL_CRB_DATA
WHERE 
[YEAR] = 2025
AND QUARTER = 'Q1'

)

SELECT 
	all_dpds.* ,
	crb.NUMBEROF_ACCOUNTS AS TU_NUMBEROF_ACCOUNTS,
	crb.OPENACCOUNT AS TU_OPENACCOUNT,
	crb.PERFORMING AS TU_PERFORMING,
	crb.NONPERFORMING AS TU_NONPERFORMING,
	crb.CLOSED AS TU_CLOSED,
	crb.CURRENTINARREARS AS TU_CURRENTINARREARS,
	crb.ARREARS0DAYS AS TU_ARREARS0DAYS,
	crb.MAXARREARS AS TU_MAXARREARS,
	crb.MAXARREARSLAST12MONTHS AS TU_MAXARREARSLAST12MONTHS,
	crb.MAXARREARSLAST3MONTHS AS TU_MAXARREARSLAST3MONTHS,
	crb.PRINCIPALAMOUNT AS TU_PRINCIPALAMOUNT,
	crb.SCHEDULEDPAYMENTAMT AS TU_SCHEDULEDPAYMENTAMT,
	crb.CREDITAPPLICATIONSDONE AS TU_CREDITAPPLICATIONSDONE,
	crb.CURRENTBALANCEAMOUNT AS TU_CURRENTBALANCEAMOUNT,
	crb.SUBSCRIBERCURRENTBALANCEAMOUNT AS TU_SUBSCRIBERCURRENTBALANCEAMOUNT,
	crb.PASTDUEAMOUNT AS TU_PASTDUEAMOUNT,
	crb.NUMBEROFENQUIRIES AS TU_NUMBEROFENQUIRIES,
	crb.ENQUIRIES30DAYS AS TU_ENQUIRIES30DAYS,
	crb.ENQUIRIES90DAYS AS TU_ENQUIRIES90DAYS,
	crb.CRB_TU_SCORE AS CRB_TU_SCORE, 
	crb.MOBILE_TOTAL AS TU_MOBILE_TOTAL,
	crb.MOBILE_PERFORMING AS TU_MOBILE_PERFORMING,
	crb.MOBILE_NONPERFORMING AS TU_MOBILE_NONPERFORMING,
	crb.MOBILE_PRINCIPALAMOUNT AS TU_MOBILE_PRINCIPALAMOUNT,
	ppc.PPC

FROM all_dpds
LEFT JOIN crb_data crb
ON all_dpds.CUSTOMER = crb.CLIENTID

LEFT JOIN dbcba.RETAIL_PPC ppc
ON ppc.CUSTOMER = all_dpds.CUSTOMER
WHERE 
all_dpds.max_dpd_train_test BETWEEN 0 AND 14






select *
from dbcba.RETAIL_PPC ppc
where CUSTOMER = '185393'
and LOAD_DATE = (select max(LOAD_DATE) from dbcba.RETAIL_PPC)